### ISSUE TITLE
Compilation problem with PDF/A

### ISSUE THREAD

**Issue by aryamazaheri** [tudace/tuda_latex_templates#10]
I am trying to turn off PDF/A because I get this error:
`TUDaPub error: "outdated-pdfx" Your Version of the PDFx-package is too old to support all methods required by tudapubs pdfa-mode. Either update your TeX-distribution or switch to pdfa=false. For immediate help type H <return>.`

But even trying to turn off PDF/A gives me this error:
`Class tudapub Error: You cannot use \Metadata\ with pdfa=false.. }`

What is the solution? Do I need to really update my TeX distribution?

**Comment by BenK3nobi** [comment]
You can comment the metadata, such that it is not taken into account anymore. 
As far as I got it, they are only needed if you want to use the PDF/A option.
Should work then.

**Comment by TeXhackse** [comment]
Sorry, I somehow dropped that Ticket. 

First of all, yes you should update to get it working properly.

The second option is to switch to `pdfa=false` and not use the `\Metadata` command.
The Fallback does the same and automatically falls back to `pdfa=false`. Therefore you get the second error, since `\Metadata` is still used.

**Comment by TeXhackse** [comment]
@aryamazaheri, did it help out? Is there still anything we could help with that?

**Comment by TeXhackse** [comment]
Due to no additional info I will close this template as resolved.
