### ISSUE TITLE
"kvoptions.sty" not found

### ISSUE THREAD

**Issue by FlixXIV** [tudace/tuda_latex_templates#104]
Hello,

since the recent update of the tuda-ci package miktex isn't able to run any kind of tuda-document. The problem is that it can't find the "kvoptions.sty" when it uses the "hyperref.sty"-file. 

I hope for your help.

**Comment by TeXhackse** [comment]
Hi,
this is not directly causes by tuda-ci because it's an indirect dependency. So you probably updated other packages as well. Since you already realized it's caused by hyperref, probably that one, or the oberdiek bundle. 

You can simply fix this (like every missing xxx.sty or xxx.cls error) by installing the corresponding package.
In this case kvoptions.

So just install that using (in your case) the miktex package manager.
