### ISSUE TITLE
Issue with PDF/A conformance

### ISSUE THREAD

**Issue by luth1um** [tudace/tuda_latex_templates#106]
Hi,

I might have found an issue with PDF/A conformance. When I check the documentation files that are uploaded to CTAN, I get the following error report (for DEMO-TUDaThesis.pdf):

[htmlReport.html.zip](https://github.com/tudace/tuda_latex_templates/files/3911369/htmlReport.html.zip).

I get the same error messages when build the PDF from source myself.

I used veraPDF (EU-funded open source project) for conformance checking but the error messages are not really helpful as you can see yourself in the report. It seems that there are problems with the Roboto font but apart from that I can't "decrypt" what's going on. I read at several places that Adobe Acrobat Pro gives better error messages but I don't have access to that tool.

Is there somewhere a problem on my side or is this a bug?

**Comment by TeXhackse** [comment]
I will recheck to ensure but the validation for the pdfs has been done before uploading, and those were valid. At least since we enforece Type1 fonts with luatex and xetex if `pdfa=true`. I rechecked that for my uploaded bundle now. The message the html shows me is one I only know from PDF/A-1b and not A-2b. But as I said, I will have a look.

**Comment by TeXhackse** [comment]
@luth1um I rechecked. So all files on CTAN + my generated ones are valid for PDF/A-2b. At least according to Acrobat + other validators, except verapdf. I will try to find out, why they differ.

If I try to validate the file for A-1b i get the same messages as you received (+ a mention of the wrong version number ofc). But According to the specification shown to me by Acrobat thats something which got changes from 1 to 2. Actually that's the case why we moved to 2b. Because the requirements for fonts differ.

Therefore I got no idea what to do about this

**Comment by luth1um** [comment]
If all validators except veraPDF say that the files are valid, then they are probably valid.

I only opened this issue because student theses at TU Darmstadt are automatically validated when they are uploaded (I assume that's the reason why you included PDF/A conformance for the templates). So I guess if the servers of the university don't complain about the template, then this issue can be closed.

Anyway, thanks for double-checking everything!

**Comment by TeXhackse** [comment]
Since the enforcement to the Type1 fonts, we had no problems with the upload, beside people used graphics which used non-embedded fonts. Maybe that hint might be helpfull as well. I close this then.
