### ISSUE TITLE
Example file not compiling

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#11]
Hello,

I downloaded the files and copied them into my LocalTeX folder where my other LaTeX files are installed. Then I updated the filename database and tried to compile the example file "DEMO-TUDaThesis" to see what it looked like. I got the following error messages "Undefined control sequence. ...g TU Darmstadt's Coporate Desing (TUDa-CI)}" on line 4 of the file tudapub.cls and "File `URspecialopts.sty' not found. \Define@specialopt@Module" on line 9 of the same file. Can you explain me what went wrong?

Thank you

**Comment by orkr1st** [comment]
i get a similar error, when trying to compile the DEMO-TUDaPhD.tex file with lualatex (Ubuntu 18.04):
```
! Undefined control sequence.                                                                   
<argument> \filedate                                                                            
                      \ifx \relax \fileversion \relax \else v\fileversion \s...                 
l.4 ...g TU Darmstadt's Coporate Desing (TUDa-CI)}  
```

**Comment by TeXhackse** [comment]
I am going to add the following information to the README.

You need to run the addlicense.sh first. 

Thing is, that I wanted prevent myself from forgetting to add the License Info. Therefore the script addlicense.sh will do so.

It also adds the data to define \fileversion and \filedate.

Without those commands you will get errors (though those will be ignoreable and you could create a PDF file without doing so).

I hope this helps. Currently thinking about another mechanism, but this seemed to be the most simple solution.

**Comment by ahbnr** [comment]
I have not tested the `addlicense.sh` solution yet, however adding the files from the latex package of the University of Regensburg resolves the `URspecialopts.sty` error for me.

Simply adding these files worked for me: http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/urcls/tex/

See also https://ctan.org/pkg/urcls

P.S. I also didn't get the `fileversion` and `filedate` errors when using the tuda-ci version from CTAN instead of GitHub: https://ctan.org/pkg/tuda-ci

**Comment by TeXhackse** [comment]
I did not see any hint on the missing URcls package. And yes this one is required. It is part of TeX Live and MikTeX so you would not have to install it on its own.


You sure dont get the fileversion message when taking the files from CTAN, because for those addlicense and preparectan have been already executed.

This is a development repo. The ctan zip file for the release also includes these data.

**Comment by marklaz** [comment]
LaTeX@TUDa web pages have been updated to avoid confusion concerning development version on github. Internal ZIP file at TUDa has been revised.

**Comment by ahbnr** [comment]
> I did not see any hint on the missing URcls package. And yes this one is required. It is part of TeX Live and MikTeX so you would not have to install it on its own.

I think that also depends on the linux distribution. In my case (Arch Linux), texlive is split into multiple packages (and I only had `texlive-most` installed), so that might explain, why I was missing urcls.

Btw. that reminds me, there was another file missing, I forgot the name, which I could fix by installing 
`texlive-langcyrillic`, in case someone else experiences further issues.

**Comment by JuLateX** [comment]
Thank you for your help. I think part of the problem comes from MikTeX which seems to break something down everytime it updates. I am trying to install TeX Live to see if it works.

**Comment by orkr1st** [comment]
Running `addlicense.sh` fixed the problem for me.

Could you maybe also mention somewhere, which texlive/miktex versions you have tested or are supposed to be used. The LTS versions of Ubuntu are still 2 years behind.

**Comment by marklaz** [comment]
Version information (TeXlive, MikTeX, MacTeX) has been added to LaTeX@TUDa web page.

Version mismatch to LaTeX in Ubuntu is a (known) problem we cannot solve, regretfully.
