### ISSUE TITLE
tlmgr: Remote repository is newer than local (2017 < 2019)

### ISSUE THREAD

**Issue by ArashJavan** [tudace/tuda_latex_templates#123]
Hi,
i use ubuntu 18.04 and did install texlive through "apt". The Version available on the latest LTS Ubutnu (18.04) is "2017". After that i tried to install tuda-ci:
`sudo tlmgr install tuda-ci`

Unfortunately i get following error:
```
  tlmgr: Remote repository is newer than local (2017 < 2019)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
```
i found some hints about this issue in stackoverflow, but none of them works.
After that i tried to just download the package from CTAN and extract it in my latex-Project-directory, but compiling gives me follwoing error:

`TUDaPub error: "outdated-pdfx" Your Version of the PDFx-package is too old to support all methods required by tudapubs pdfa-mode. Either update your TeX-distribution or switch to pdfa=false. For immediate help type H <return>.
`
I wondering why the CTAN-version of tuda-ci is not compatible with the latest ubutntu, since most of the ubutntu-users install texlive using "apt" and standard ubutnu-repos and not through donwloaing and manually installing!

Any idea what i should do?
Thanks

**Comment by schoeps** [comment]
Please do not use your linux package manager for installation but install a proper texlive manually yourself. See the recent discussion in https://github.com/tudace/tuda_latex_templates/issues/121.

**Comment by TeXhackse** [comment]
@ArashJavan Did you check https://tug.org/texlive/upgrade.html? because there you would also find additional information on that. If you already use tlmgr you should be able to use that way to upgrade.
Usually download the update-tlmgr-latest script and run it. Would fix that. That's exactly what the message told you.

@schoeps The package management would not install tlmgr. That's why I think it was already installed via CTAN. Just not updated for years.

**Comment by ArashJavan** [comment]
@schoeps , @TeXhackse 
thanks, i installed texlive manually and it works now.
