### ISSUE TITLE
Beamer: titlegraphic wrong scaling / not centered

### ISSUE THREAD

**Issue by steven-lang** [tudace/tuda_latex_templates#129]
When using the `\titlegraphic` option in beamer as follow:

```
\titlegraphic{\includegraphics{../res/Quanser--BallBalancer_cropped_recolored.png}}
```

with [this image](https://drive.google.com/open?id=1dcN1W9ScdpBk9CFzZ1TurT_txnPoMI-a), I get [this title page](https://drive.google.com/open?id=1C57N6__Ys71RPEs8nHSLSA2uQboJ3MBr).

When specifying the height:

```
\titlegraphic{\includegraphics[height=100px]{../res/Quanser--BallBalancer_cropped_recolored.png}}
```

I get [this](https://drive.google.com/open?id=1uqIvLXdNAL9esWOncTLYwJnbZ2-h32oq).

Is this the expected result?

How can I get my titlegraphic properly scaled and centered in the remaining space on the title page?

When I add `\centerline` in `\titlegraphic`:

```
\titlegraphic{\centerline{\includegraphics[height=100px]{../res/Quanser--BallBalancer_cropped_recolored.png}}}
```

the title page looks like [this](https://drive.google.com/open?id=1Zc0fAVVdusAKtUqixtrf3Ft3EJ0z98iw).

I feel like I'm doing something wrong here?

**Comment by TeXhackse** [comment]
Thanks for the report. Indeed we did center the image. This is due to all examples we found were able to be cropped. You example is not.

I will patch the titlegraphic to be centered. Sorry for that issue.

**Comment by TeXhackse** [comment]
@steven-lang Patch is applied, will be included in the next release, but you can see the minimal change by having a look at the commit. Could also be resolved by a local copy of that file.

Beside that (just because I want to mention), you should not use `100px` as a length scale, maybe think about using the descripted `\height`/`\width` macros for scaling. This would fit automatically.

**Comment by steven-lang** [comment]
Thanks, it's horizontally centered now. But there is stil zero vertical space between the header and the image. Adding a `\vspace{1em}` before the `\includegraphic` statement has no effect.

What do you mean by the `\height` and `\width` macros?

**Comment by TeXhackse** [comment]
So we now switch to a different and more general LaTeX question.

The Template defines `\height` and `\width` to allow the user to use the whole box reserved for the `\titlegraphic`. This is described in the Demo files. 

Thing is, it is an absolute placement, since the design guideline required us to place the image without any additional space. You example is nothing intended by the design guideline.

To add extra padding outside the image you could use frameboxes:

```
\titlegraphic{\colorbox{red}{\includegraphics[height=.4\height]{example-image-16x9}}}
```
The value of distance is `\fboxsep` and can of course be locally adjusted.
This is just a random example. Replace color, image and size in the way you prefer.


Another way would be to vertically center it. Activating this in general is not a good idea, because in this way an image with has full `\width` but only a part of the `\height` would still be consistent with the rules.

Easiest way to vertically center that would then be to place a box of height `\height` inside the titlegraphic area and fill it with glue. Speaking TeX this would be

```
\titlegraphic{\vbox to \height {%
   \vfill
   \includegraphics[height=.4\height]{example-image-16x9}
   \vfill
}}
```
