### ISSUE TITLE
Distance of the caption to the top a the page

### ISSUE THREAD

**Issue by SidMueller1337** [tudace/tuda_latex_templates#138]
Is it possible to shorten the distance of a caption to the front of the page?

![Bildschirmfoto 2020-01-24 um 10 54 40](https://user-images.githubusercontent.com/60255943/73060381-fcc56480-3e97-11ea-8c36-079acd6273d1.png)

**Comment by schoeps** [comment]
Caption or Heading (I assume the latter?) Yes, it is possible to change the distances (just google for some variation of the words `latex`, `heading`, `chater` `distance` `koma` and you should find something helpful). We do not recommend to change this since the latex design is following the official guidelines of TU Darmstadt, see also https://github.com/tudace/tuda_latex_templates/issues/28.
