### ISSUE TITLE
Replacement for tudexercise

### ISSUE THREAD

**Issue by Lex999** [tudace/tuda_latex_templates#14]
What is the best way to replace the old "tudexercise" class for creating exercises and exams?

**Comment by TeXhackse** [comment]
We are planning to create a fitting variant and corresponding template. Currently there are some details to be discussed. We keep you informed on the status.

If you got special or somehow specific usecases, we are glad if you inform us about those asap. Maybe we are also able to consider those during the creation.

Since all the templates require a lot of discussion due to the Corporate Design Guidelines this process can take some time.

**Comment by Lex999** [comment]
The only thing we have changed in the old template was to have the environments "examheaderodd" for odd page numbers and "examheadereven" for even page numbers instead of only "examheader". It would be nice if this would be built in by default.

**Comment by TeXhackse** [comment]
The template is currently on an extra development branch if you would like to try that one.
There will be a "compatibility" mode to ensure you can use the old Syntax as well. Though I'd recommend to use the new syntax due to some advantages in being compatbible to the base class, which is scrartcl and also with other packages.

**Comment by TeXhackse** [comment]
@Lex999 thanks, I implemented the feature just didn't add the option. Will follow asap.

**Comment by TeXhackse** [comment]
Currently all planned features have been added. 
See https://github.com/tudace/tuda_latex_templates/releases/tag/v1.2-beta for new demo bundle. Some tests are still running. though it seems close to be released.
