### ISSUE TITLE
Use sffamily as default font for captions

### ISSUE THREAD

**Issue by reg-is** [tudace/tuda_latex_templates#143]
I want to make parts of my caption italic but neither `\textit` nor `\emph` is working.
Making text bold with `\textbf` is working fine.
In the table of figures, italic text is displayed correctly but not in the caption underneath the figure.
Is it a bug or choice made on purpose?

**Comment by schoeps** [comment]
MWE please.

**Comment by reg-is** [comment]
> MWE please.

Here https://www.overleaf.com/6779733697bsbbhqnbxfqy

**Comment by TeXhackse** [comment]
This is because the font which shall be used (as all similar ones) does not have an italic style. 

You can try to find a fitting one, but I guess in this case it would be easier to change the font for the captions and use the normal text one.

Currently the setting is using 
```
\addtokomafont{captionlabel}{\accentfont}
\addtokomafont{caption}{\accentfont}
```
while `\accentfont` is Roboto Slab.
you can change this by doing a `\setkomafont` for these elements

**Comment by marklaz** [comment]
Ok, thought about it.

As Robot Slab substitutes Stafford, I would suggest to change to Roboto, which substitutes Frontpage, for captions as default (cf. p. 14 of the CD manual).

**Comment by TeXhackse** [comment]
rechecked that and am confused now. i know we had Roboto there at the beginning, but can't remember why we changed that. Anyway. will be switching back then.
