### ISSUE TITLE
Text/logos at the bottom of TUDaPub title page

### ISSUE THREAD

**Issue by op3** [tudace/tuda_latex_templates#165]
As discussed [here](https://github.com/tudace/tuda_latex_templates/issues/29), the old fkp LaTeX classes included a `\sponsor{…}` macro to place sponsor information on the title page of theses. In contrast to the solution discussed in the aforementioned issue, this macro enabled one to place text and/or images at the very bottom of the title page, similar to way sponsors are placed using the leaflet class.

In my group, this has been used to place text at the bottom of the title page (“This work has been supported by …”) in conjunction with logos. Is something similar still possible?

And is it actually allowed by the corporate design? As I understand it (see page 34 of the cd manual), it should be allowed to place logos in the footer of the title page, but not text.

However, the `\AddSponsor{…}` macro from the leaflet class is apparently not available in the TUDaPub class.

**Comment by TeXhackse** [comment]
You are right, the same mechanism as I built for tudaleaflet is not yet existing to tudapub. This is because it was not requested and the tudaleaflet has been built independently. There is a bunch of different requirements, but yes, it would be possible to extend. About whats allowed or not there is a bunch of variants, especially if one includes the older versions of corporate design guidelines, which were more specific. But that decision is not part of my responsibility.

Without  an extension it's already possible to hack the titlepage that way, by using the titlegraphic box and fill it with custom content. I can try to find some free time for an example, if you can show me the layout, you'd try to archieve. But it could take some days, so I hope it's not too urgent.
