### ISSUE TITLE
set tudaletter with narrow textwidth

### ISSUE THREAD

**Issue by flx-wlf** [tudace/tuda_latex_templates#172]
I am aware that this does not comply with the corporate design, but would it be possible to add an option to set entire multi-page letters with a narrow textwidth, following the style of the official word-templates?

**Comment by marklaz** [comment]
We might think about that in a future release. But as it is not CD, it will have a low priority from our side.

**Comment by schoeps** [comment]
Most letters from the central administration of TU Darmstadt are disregarding the odd change of textwidth (probably because Word cannot do it?). 

@TeXhackse I wrote the following hack (redefining `\textwidth` and use of `\everypar`) if a user wants to disable the change of textwidth for pages >1. Do you know a better way?
```
\documentclass[
accentcolor=3d,
premium=true,
pdfa=true,
]{tudaletter}
\usepackage{blindtext}
\setlength{\global\textwidth}{12cm}
\begin{document}
\begin{letter}{}
\setkomavar{subject}{Subject}
\opening{Dear all,}
\everypar{}
\par\blindtext
\par\blindtext
\par\blindtext
\par\blindtext
\par\blindtext
\par\blindtext
\par\blindtext
\par\blindtext
\par\blindtext
\par\blindtext
\closing{Best regards}
\end{letter}
\end{document}
```

**Comment by TeXhackse** [comment]
Yes, Word cannot do it. This is actually why I spend that uch time on the implementation to be conform to the Guidelines, because Word is not ;-) 

I have an implementation for this already, Sadly I am but struggeling with the current situation. This is why everything is working much slower atm. I am trying to finish the major update asap, but sadly I cannot about promise about it atm. I am sorry. But I included this in the features requsts of the department of mechanical engineering and it will be released all at once. Because this makes it a bit easier for me. 

I hope this is okay.

**Comment by schoeps** [comment]
Don't worry. There is no time pressure on this. I will use my ugly hack above for the time being :)
