### ISSUE TITLE
Class not found on Mac

### ISSUE THREAD

**Issue by katjamuench** [tudace/tuda_latex_templates#174]
I am using TeXShop with MacTex and downloaded and unzipped the folder at the top layer of the local latex tree. However, I keep getting the following error:

! LaTeX Error: File `tudapub.cls' not found.

**Comment by TeXhackse** [comment]
You would have to update the file name database. This can be either be done using the MacTeX setttings or running mktexlsr in the terminal. this might require root privileges.

But you should be able to install the package directly, because it is part of TeX Live. So maybe you simply should update MacTeX and install the package from there.

**Comment by schoeps** [comment]
>simply should update MacTeX and install the package from there.

The app is called "Tex Live Utility"

**Comment by katjamuench** [comment]
Thank you so much! I tried this and received the following error message: 

![image](https://user-images.githubusercontent.com/34099756/78790775-490c4500-79af-11ea-9651-49552b0a48f3.png)

**Comment by TeXhackse** [comment]
ah thats fine.

you should just install the package via that. you cannot update the currently installed ones any further, until Tex Live 2020 is finished.

**Comment by schoeps** [comment]
...and it's probably a good idea to remove your local installation (to avoid future confusion)

**Comment by schoeps** [comment]
@katjamuench problem solved? (by the way mactex 2020 is now released, so installing it from scratch makes even more sense now)

**Comment by TeXhackse** [comment]
I'll close this, as it seems to be solved.
