### ISSUE TITLE
Exercise point field

### ISSUE THREAD

**Issue by cvoelcker** [tudace/tuda_latex_templates#176]
Hi, thanks for all your work. Is there a nice and preferred way to add points to the ```task``` and ```subtask``` environments? If not, would it be viable to add that as an optional field? Maybe even add the text "Punkte/points" after the numerical value?

**Comment by TeXhackse** [comment]
Hi, sorry for the late answer.
I somehow thought, we would have such a feature. But either I am blind or we do now. Since it's nothing too complicated, I will add that during the weekend, there still some small things to fix anyway.  There will be an option-key named points, so you will be able to use:

```
\begin{task}[points=xxx]{Title}
```
the default will be a braced value after the title, text is optional.
