### ISSUE TITLE
Table of contents: Page number alignment

### ISSUE THREAD

**Issue by ahueck** [tudace/tuda_latex_templates#185]
Looking at the table of contents of my document, I realised that the (right) aligned page numbers only work for pages <= 2 digits:
![image](https://user-images.githubusercontent.com/11541540/81092085-60801480-8f00-11ea-888d-cf82bae8dd88.png)

The alignment fails for a chapter of mine when the page starts at, e.g., 90 and goes up to 100++.
See below:
![image](https://user-images.githubusercontent.com/11541540/81091911-2747a480-8f00-11ea-9198-c66d7ab050b6.png)

Can this be fixed ?

**Comment by TeXhackse** [comment]
This is caused by the way LaTeX generally creates the table of contents. The pagenumberbox has a fixed width. It's discussed in the KOMA-Script documentation, but you can use the following to adjust the pagenumberboxwidth:
```
\DeclareTOCStyleEntry[pagenumberwidth=3.5ex]{default}{chapter}
\DeclareTOCStyleEntries[pagenumberwidth=3.5ex ]{default}{section, subsection}
```

You could also add a mechanism to reference this, but this would require an editional compilation run. LaTeX can't know how long your document will be, when it's printing the toc. If you're interested in an implementation of this, let me know. But since this would change the required compilation runs, this is no option for a general implementation. This is why it's not done for basic document classes.
