### ISSUE TITLE
Disable reviewer in PhD Thesis?

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#190]
Is it possible to have no information regarding the potential reviewers of a Ph.D. thesis? I tried to delete the `\reviewer{...}` command which did not work, and using the command without an argument still displays `1. Gutachter:` on the title page

**Comment by TeXhackse** [comment]
You don't receive an error message when deleting `\reviewer`? Because then we would have a bug.

It's not supported, because the phd option marks this information as required. 

If you remove the `\reviewer` you should receive an Error message to inform you about this fact. 
Leaving it empty will remove the error but treat is line an empty reviewer name. 

But:

So one possibility would be to use a thesis type which differs from phd and set the the data manually, which might be the rather obvious way.

Or to remove the reviewer from the list of required fields:

```
\ExplSyntaxOn
\clist_gremove_all:Nn  \g_TUDa_Required_title_data_clist  {reviewer}
\ExplSyntaxOff
```
placing this in your preamble will overwrite the requirement, set by `type=dr`

**Comment by AlexVHopp** [comment]
Thank you for the quick answer. I did receive an error message that stated that the `reviewer` field was necessary, sorry for the confusion. I included the code that you provided here and this worked for me, thank you very much!

**Comment by Spiekerooger1** [comment]
Hi,
ist es möglich reviewer auch von der list of required fields für type=bachelor zu streichen?

VG
