### ISSUE TITLE
How to modify the line space on template -thesis- type -master-?

### ISSUE THREAD

**Issue by LCCardenas** [tudace/tuda_latex_templates#191]
Hi,
I would like to modify the line space on that particular kind of document. I would usually do that with the package `{setspace}` and `\onehalfspacing`, but I was wondering if there's a better way to achieve the same effect with this template. 
Thank you.

**Comment by schoeps** [comment]
We are using the koma class and its manual proposes also `setspace`, so I don't think there is something better.

**Comment by TeXhackse** [comment]
This is correct. We did not add a special mechanism, because usually the usage of setspace varies from document to document, depending on your decision about singlespaced lists or not. So you will have to adjust this yourself.

Please ensure to pay attention to the fact, that we recalc the lengths after the titlepage. So one should not activate setspace for the title material. This is mentioned in the documentation as well.
