### ISSUE TITLE
B5 paper format in TUDAThesis

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#208]
For publishing my PhDThesis, I would like to change the paper size of my current version to B5. It seems however that it is only possible to change the format to A0 to A6 (at least via the option `paper=...`), how can I use the B5 or a similar format?

**Comment by TeXhackse** [comment]
This is true and depends on the fact, that the `paper= ` is also used to determine the fontsize for the title. The design guideline does not offer any sizes beside the a formats. But of course you can use `custommargins=geometry` and then `\geometry{b5paper, <input your margin setup here>}`.

I did not find time to test it but based on the construction of the template this should work.
Please let me know if there are any issues and close this issue otherwise.
