### ISSUE TITLE
Potential optionclash with microtype

### ISSUE THREAD

**Issue by martin-fzd** [tudace/tuda_latex_templates#225]
The Microtype package is included in the demo files.
https://github.com/tudace/tuda_latex_templates/blob/aea647e9c1468423d0cc3a69c3022c2b88a8c765/example/DEMO-TUDaPhD.tex#L31

This is also listed in the `tudafonts.sty` file as `RequirePackage`:

https://github.com/tudace/tuda_latex_templates/blob/aea647e9c1468423d0cc3a69c3022c2b88a8c765/tex/tudafonts.sty#L36

This can lead to an option clash if the user wants to pass additional options for the microtype package.
My workaround so far is to include the required package settings in `tudafonts.sty` , e.g. `\RequirePackage[superfancyfeature=true]{microtype}` and to remove the call from the main .tex file
To avoid this problem completely, should the package call be removed from one of the two places?

**Comment by TeXhackse** [comment]
This is not an option. I'll try to explain why:
The microtype package is only used there in case of enforced Type1 font (which is luckily no longer necessary to be enabled by default, see v3.03) because otherwise there will be empty glyphs inserted for some ligatures. 

This means microtype is not a basic requirement. This is also the reason why it's not added in every template. I only was asked to add some recommended packages to the thesis variants.

But you are right, we should mention that in the documentation as one special of Type1 use.

Anyway, you can workaround option clashes easily without modifying the package file (this is generally the best workaround for these ;-) :
```
\PassOptionsToPackage{superfancyfeature=true, maybe another one, …}{microtype}
%then load the package/class which automatically loads the package, in this case:
\documentclass[…]{tudapub}

\usepackage{microtype}
```

**Comment by martin-fzd** [comment]
That works for me. Thank you for your detailed description. Issue can be closed.
