### ISSUE TITLE
Set custom margins

### ISSUE THREAD

**Issue by tudtemp** [tudace/tuda_latex_templates#230]
Hi,

I need to set custom margins to match the requirements of my seminar paper. I already tried this:

`\usepackage{geometry}
 \geometry{
 reset,
 top=30mm,
 left=30mm,
 right=20mm,
 bottom=25mm,
 }`

The result is weird. There is no difference, except for the header which is extended (but only for pages without \chapter tag).

**Comment by TeXhackse** [comment]
Hi, 
The titlepage's margins differ from the other pages. This is why `\maketitle` will reset the margins as well.
You can use custom margins using the class option `custommargins=geometry` and then using your setup
```
 \geometry{ reset, top=30mm, left=30mm, right=20mm, bottom=25mm, }
```
I am currently working on copying this information to all variants of demo documents, because it currenctly can only be found in the thesis-variants.

**Comment by tudtemp** [comment]
Thank you :-)

This is what I did to set the margins:

- Changed `custommargins=true` to `custommargins=geometry` in the `\documentclass` section.
- Added ` \geometry{ reset, top=30mm, left=30mm, right=20mm, bottom=25mm, }` below the `\documentclass` section.
