### ISSUE TITLE
\textbf{} not working after packages update

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#245]
Hello,

I am not sure the question should go on this GitHub. I did a packages update this morning with TeX Live Manager (all updatable packages) to get the V3.06 of the tuda-ci package. Since then, `\textbf{}` no longer works and I receive the following warning:

> Font shape `T1/XCharter(0)/m/n' undefined(Font) using `T1/cmr/m/n' instead

I checked with an older version of my thesis which was last compiled with `\textbf{}` working, it does not work anymore either so I do not think it is due to any changes in the thesis itself. Do you have an idea what is going on?

Thank you

**Comment by TeXhackse** [comment]
It's a bit difficult to answer this without additional information.

Can you please give me a log file? (maybe even the file you try to compile)

**Comment by JuLateX** [comment]
Sure. I made a minimum working example to make the problem more visible.

I just noticed that the `\textit{}` is also not working anymore. There is supposed to be bold and italics in the abbreviations section.

Log file:
[Log file.txt](https://github.com/tudace/tuda_latex_templates/files/5415790/Log.file.txt)

Thesis file (main file with two input files):
[Thesis_test.zip](https://github.com/tudace/tuda_latex_templates/files/5415809/Thesis_test.zip)

**Comment by TeXhackse** [comment]
It's not directly related to tuda-ci. 

#### Explanation why it has not been a problem before:
We disabled the enforcement of T1 fonts with some older version and you are still using Type1 fonts.  With LuaLaTeX one should not use T1 fonts if not necessary. It had been necessary because some older version of Roboto missed some metrics to be correctly embedded info PDF/A.
Not tuda-ci is using fontspec as expected for LuaLaTeX, but you are loading `\usepackage[T1]{fontenc}` which disables fontspecs font loading mechanism. And this disables the complete font selection of tuda-ci.



#### possible solutions
You now have 3 options.
1. remove the fontenc package (this would be the best option the other ones are hacks)
This will disable the font you use for the dedication. This font is not available as OTF/TTF, so in this case you would have to change that one. (https://www.tug.org/FontCatalogue/calligraphicalfonts.html might help with that)
2. pdfLaTeX
You can either switch to pdflatex which will probably lead to some issues if you want to use pdfa.
3. Reenable the T1 enforcement even if you are in lualatex (you can then remove the fontenc package anyway, because it will be preloaded) This can be archieved by adding `\PassOptionsToPackage{T1}{tudafonts}` before loading the class

**Comment by JuLateX** [comment]
The first option is really good. Apparently the font I use in the dedication also works without the fontenc package and now the bold and italics are back.

Thank you!

**Comment by TeXhackse** [comment]
Just because this might cause issues:
the font you use for the dedication is a Type 1 font. Without fontenc you won't be able to get „real“ umlauts or some other special characters in there. I don't think you will face this, but you should pay attention.
