### ISSUE TITLE
custom exercise numbers (was: Is there a way to support exercise types?)

### ISSUE THREAD

**Issue by maralorn** [tudace/tuda_latex_templates#248]
Hey,

first thanks for this LaTeX class. It's really great.

At our department (mathematics) basically all courses distinguish between group exercises and and homework exercises on the same sheet. To support that I would need four things

1. define a prefix for the exercise number e.g. "H5.1" or "G5.1"
2.  have independent counters per prefix or a way to reset the counter when changing the prefix
3. (this might be tricky) have some way to enable solutions selectively. Our current template based on the old latex class supports the three different keys "uebung|gruppenloesung|loesungen", but I am not picky on what the right way would be.
4. Insert a section header between at the start of each type. (This one is trivial I guess.)

I am not sure if having all of this features in the exercise class is within the scope of this project. For me right now I would already be very glad if you gave me any pointers as to what parts of this I can achieve manually and how. I will also try to find out by reading the source, but I thought I should open an issue either way to see what you think.

**Comment by TeXhackse** [comment]
Hi,
first of all:

Yes, of corse there is a way! (SCNR)

As you already said it's department specific. But everything can be archieved already if you know how to use the features.
In case the maths departments wants a departments specific extension, it's possible to discuss that via email, that's nothing for this issue tracker.

-------------------------
Because you said, you'd like to read the source I will only give some hints about the construction I'd use. 

First a small Question:
Is the prefix a letter or alphanumeric? In the latter case, please let me know, and ignore what I wrote about 1. and 2. (i edited your issue so we get a markdown enumerate) Alphanumeric one would to defining a counter + add that one as a resetcounter to the task counter. So task will always be resetted when the prefixcounter changes.

1. You can simply redefine the output of the counter called task `\thetask` if you want the prefix to be included in references. Otherwhise you can also redefine the macro `\taskformat`.

2. Create a macro to combine the setup of the prefixmacro of 1. with a counter reset. 
 So I'd suggest a `\switchprefix{<prefix>}` macro which includes change of 1. and 2.

3. Well not really tricky, you currently can turn on/off the soliuion for every task itself.  So you only want to add a hook and some tagging to each task. The “easiest” way to do so would be the definition of a grouping environment, which could set the boolean option for the solution environment. Another alternative would be to „copy“ the solution environment and create similar ones depending on other booleans. This depends on how you would like to mark a task to be a member of one of the groups.

4. Well, did you try to use `\section`?

**Comment by maralorn** [comment]
Something along the lines of
```
\subsection*{Hausübung}
\setcounter{task}{0}
\renewcommand{\taskformat}{H\thetask}
```
did most of the trick. thank you for pointing me to the that command.

Only thing missing as step 3. I must admit that my latex foo is not very strong. So I am not sure what you mean with a "grouping environment".

**Comment by TeXhackse** [comment]
*Hint*: You ssould use `\renewcommand*`  instead of `\renewcommand` in that context.

#### Remark
The following explanation is simplified. I'd implement that different but thought it might be easier for you to use l2-Syntax as far as possible. I'd implement it, but adding a group-key to the task options. But this would require you to use more of expl3 syntax.
The boolean used to control the solution is called `\l_ptxcd_ex_solution_bool ` (v3.0 or newer) and you can to temporary change that one depending on the task type.

#### Explanations 
If you define an environment like
```
\newenvironment{taskgroupA}{
   <change something about the solution here>
}{}
```
This will group the content. Which means if you change the value of the solution boolean inside, it will be reset at the end.
```
\begin{taskgroupA}
   include the tasks which shall depend on that taskgroup
\end{taskgroupA}
```

The solution is controlled using the l3keys module. This means you can change the value by
```
\ExplSyntaxOn
\keys_set:nn {ptxcd/task}{solution=<true/false>}

%or if you want to make that available in l2 Syntax:
\newcommand*{\setTaskOption}[1]{\keys_set:nn {ptxcd/task}{solution=#1}}

%afterwards you can use 
\setTaskOption{solution=<true/false>}
\ExplSyntaxOff
```
You now can combine both
```
\newenvironment{taskgroupA}{%
   \setTaskOption{solution=<true/false>}%
   \ignorespaces%
}{}
```



#### Create something like a boolean
Since I don't know if you know about basic booleans in TeX you could either change the redefinition to switch the Groups, or you create a boolean structure using
```
\newif\iftaskgroupA
```
Afterwards you can use `\taskgroupAtrue` and `\taskgroupAfalse` and 
```
\iftaskgroupA
 do if true
\else
  do if false
\fi
```
to check the value.

If you combine this with the definition of the environment, you could set all these to a department specific configuration file to keep the main files clean.

**Comment by Trynnr** [comment]
As an addition, here is a way to adjust the numbering of subtask*, as it took me a while to do this myself. Maybe this will save others a little time.

`\renewcommand*{\thesubtask}{\arabic{subtask}}`
`\renewcommand*{\subtaskformat}{\thetask{}.\thesubtask\enskip}`

This will change the output e.g. from "1c) Subtask" to "1.3 Subtask".

**Comment by TeXhackse** [comment]
Please pay attention, that labels will then only give you the “3” for the subtask. 
In case you want to have 1.3 as a reference you'd have to redefine it as part of `\thesubtask`.

This is generally the way to reference counters, nothing tuda-ci specific. `\the<countername>` is always used to access the value for output.
