### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by PITEC27** [tudace/tuda_latex_templates#25]
Hi, it's not possible to add a Glossary

how i normally add:

****************************************************
\usepackage[acronym,xindy,toc]{glossaries} 
\makeglossaries

\loadglsentries{pages/glossary.tex} 

\begin{document} 
.....
\printglossaries
...
\end{document}
****************************************************

Is this problem known? Is there already a solution?

With the new Corporate Design there is also a another problem.
The template for the thesis declares the documentclass as 'tudapub', but it should be 'tudathesis'

****************************************************
\documentclass[
...
]{tudapub}
****************************************************

but if I declare it as 'tudathesis', the file 'tudathesis.cls' is missing

**Comment by TeXhackse** [comment]
I split it up into 2: 
### Lets start with the class name:

> The template for the thesis declares the documentclass as 'tudapub', but it should be 'tudathesis'

Why should it be like that?
The complete Bundle is configured that for all kind of report like documents, there is only one documentclass which is tudapub.

The only difference is the tudathesis.cfg file

### To your glossaries Question
This works fine. Maybe you forgot to add `\gls` references or to run xindy? There is no reason for any kind of conflict with the glossaries package or mechanism.

**Comment by PITEC27** [comment]
Thanks for your quick reply!

Since there is 'pubthesis', it is very misunderstanding , I think.
So the one question is then clarified, thank you.

**The glossary thing**
I tried a more simple way, but it was not successful either.  What works is the linking, but it does not show me the glossary page
I oriented myself to the following code.
I use overleaf. I also checked other work's and it works, but I see no difference in the code.

**************************************************************
copied from https://www.overleaf.com/learn/latex/Glossaries

\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{glossaries}
 
\makeglossaries
 
\newglossaryentry{latex}
{
    name=latex,
    description={Is a mark up language specially suited 
    for scientific documents}
}
 
\newglossaryentry{maths}
{
    name=mathematics,
    description={Mathematics is what mathematicians do}
}
 
\title{How to create a glossary}
\author{ }
\date{ }
 
\begin{document}
\maketitle
 
The \Gls{latex} typesetting markup language is specially suitable 
for documents that include \gls{maths}. 
 
\clearpage
 
\printglossaries
 
\end{document}
**************************************************************

**Comment by TeXhackse** [comment]
I actually don't get the pubthesis point. There is no package/class named by that.

Anyway, to Overleaf:
Overleaf is not using a current TeX Installation. Usually it's about 2 years outdated. Since It's not allowed to Upload the Logo files there I connot publish the tuda-ci Files as Template over there. But I can get it working. The important part is, that you have to upload all necessary files to your project. 
If you do so, it works fine. Just tested that.

So the problem might be somewhere else. Did you check the log files for errors? Overleaf usually encourages users to ignore error messages.

Another possibility will be to share the Overleaf project. But since having a look at that is not actual part of my job, I won't find time to check that before the weekend. If this is okay, my Overleaf Account is tex@mareipeischl.de

**Comment by PITEC27** [comment]
I found the problem. For those people who also use overleaf:
For a better overview I uploaded the files directly into a separate folder. Over all latex works without a problem. But I had the problem with the glossary and maybe there is more.
Now it works by simply uploading it first to the free area and after that putting all the files into the separate folder.
Thank you TeXhackse for your time.
