### ISSUE TITLE
How to _not_ automatically capitalize every first letter of titles listed in the bibliography (authoryear-style)?

### ISSUE THREAD

**Issue by geisenhofer** [tudace/tuda_latex_templates#253]
Maybe one of you has got the answer to the general LaTeX question mentioned in the title.
I am using BibLaTeX/Biber and I want to keep the original capitalization from the bib-File and not to overwrite it...

**Orginial source:** _This is publication number one_ (This is what I want to have)
**Authoryear:** _This is Publication Number one_

Thanks in advance!

**Comment by schoeps** [comment]
I do not have a working solution but I played with title casing in the past and I believe that googling `\DeclareFieldFormat{titlecase}` could prove helpful.

**Comment by TeXhackse** [comment]
I am confused. I just checked that and for me the basic version of BibLaTeX authoryear does not do that.

Generally `\DeclareFieldFormat{titlecase}{#1}` would change that, @schoeps is right with this, because one would use that to remove the modifier for the titlecase fields.

For further help I'd need more information on your setup.

**Comment by geisenhofer** [comment]
@TeXhackse Thanks for your reply. It made me checking the _advanded export options_ in Zotero, where the wrong capitalization style has been set by accident. Sorry for this! The problem is solved 👌
