### ISSUE TITLE
Beamer Presentations with matching pdf page numbers

### ISSUE THREAD

**Issue by miterion** [tudace/tuda_latex_templates#255]
By default the slides generated by latex beamer have their pdf page number set to the one also found on the slide. This means that a slide with multiple overlay steps is still referred to by its "actual slide number" instead of a growing offset, which increases with every added overlay.

For example the following screenshot shows the fifth slide (as seen on the bottom), which is actually the seventh slide in the deck:
![image](https://user-images.githubusercontent.com/4395770/98380128-72c24300-2048-11eb-8909-9f189dc30a31.png)

This behaviour however is currently not present in the tuda_latex_templates, which show the same slide like this:
![image](https://user-images.githubusercontent.com/4395770/98380350-bddc5600-2048-11eb-85db-39cbd850dd2d.png)

This is due to this line in the code, which deactivates this feature with the flag `pdfpagelabels=false`:
https://github.com/tudace/tuda_latex_templates/blob/388b65e5e9611dba5f92ccb8f8ea80d3ef996d71/tex/tudabeamer.cls#L58

Would it be possible to restore the behaviour of latex beamer by reactivating this option?

**Comment by TeXhackse** [comment]
Ofc you can use the standard beamer option to pass options to hyperref. So adding `hyperref={pdfpagelabels=true}` to your class option list should resolve this.

But thanks for making me try this out again, because it's viewer dependent and I realized that the issue I wanted to resolve by setting this too false might no longer exist. So If my tests run the way I expect this option will be remove for the next release anyway.

**Comment by miterion** [comment]
That is a great hint, thank you for that :)
