### ISSUE TITLE
Change font size of title

### ISSUE THREAD

**Issue by Aaron4496** [tudace/tuda_latex_templates#264]
Hello,
I´m trying to write my Master Thesis with the tudapub class. Because my title is too long I need a smaller than default font size for my title. When I try something like \title{\Large{Actual title}}, I get the error message shown in the attached picture. A change like this, should also change the font size of the title on the second page, which I do not inted.
So how do I change the font size for the title only on the very first page?

![Title_error_message](https://user-images.githubusercontent.com/74589573/99361946-229e7880-28b3-11eb-8fcb-5dbee3fc2247.png)

I define the title in the file personal setup, which looks like this.

![Title_setup](https://user-images.githubusercontent.com/74589573/99362138-63968d00-28b3-11eb-8abc-ddd526ed593a.png)

Thanks for your help
Aaron

**Comment by schoeps** [comment]
Can you please give a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) ("MWE") in plain text? This is good practice for such questions. Screenshots are less helpful since they cannot be easily copied (and are not indexed by search engines and are not accessible for all people). Secondly, given such a complicated example it's more difficult to pinpoint the error.

To your question: I do not think that the error is linked to your font size change but I did not check carefully. In either case you misunderstood the fontsize commands, they do not take arguments, see e.g. https://www.latex-kurs.de/fragen/schriftgroesse.html. In other word: `\title{\Large Titel}` should be fine.

**Comment by TeXhackse** [comment]
Nope the issue is, that he's add a macro to the field, which will be passed to the metadata. This will not work. That's why the `\Metadata` macro exists.

Anyway, we added the option `title=small` which will probably solve your issue without any adjustments.

**Comment by schoeps** [comment]
@TeXhackse why is the `\Metadata` macro not stripping commands?

**Comment by TeXhackse** [comment]
Because I don't know if the macro is a shorthand for a text or something else. So it depends on the definition of the macro and prefer throwing an error over „magic“ which will probably not been seen by the user.  We could of course use everything as a string (and if remember correctly we had discussed this before we introduced `\Metadata`).

He can use `\title` with a macro and add the pure metadata to `\Metadata` this is also described in the example.

@Aaron4496: Just another hint because I saw your manual construction for the “Kurzfassung”. You should probably use \addchap instead of the manual toc entry. + Your construction concerning the titlepage seems a bit creepy.

**Comment by schoeps** [comment]
@TeXhackse ok, this makes sense to me. I obviously forgot the previous discussions on that topic :)

**Comment by TeXhackse** [comment]
@schoeps Alright then :)

Just let me add: Generally speaking `\title{\large Title}` would also not be a really good idea. It would kill the markup. So the fontsize would be part of the title. One would prefer adjusting the font element instead.

**Comment by Aaron4496** [comment]
> 
> 
> Nope the issue is caused by the fact, that he's add a macro to the field, which will be passed to the metadata. This will not work. That's why the `\Metadata` macro exists.
> 
> Anyway, we added the option `title=small` which will probably solve your issue without any manual adjustments.



> 
> 
> Nope the issue is caused by the fact, that he's add a macro to the field, which will be passed to the metadata. This will not work. That's why the `\Metadata` macro exists.
> 
> Anyway, we added the option `title=small` which will probably solve your issue without any manual adjustments.

Thanks, title=small  solved my issue. I should have read the instructions better.

**Comment by Aaron4496** [comment]
> 
> 
> Because I don't know if the macro is a shorthand for a text or something else. So it depends on the definition of the macro and prefer throwing an error over „magic“ which will probably not been seen by the user. We could of course use everything as a string (and if remember correctly we had discussed this before we introduced `\Metadata`).
> 
> He can use `\title` with a macro and add the pure metadata to `\Metadata` this is also described in the example.
> 
> @Aaron4496: Just another hint because I saw your manual construction for the “Kurzfassung”. You should probably use \addchap instead of the manual toc entry. + Your construction concerning the titlepage seems a bit creepy.

Thanks for the help. I'll try to change that. I just got a working template that looked like that and tried starting to work from there.
