### ISSUE TITLE
English Captions

### ISSUE THREAD

**Issue by ATuda-ciUser** [tudace/tuda_latex_templates#265]
I hope I do not double an issue, but at least I do not find it.

I am using the tuda-ci thesis-class with the option "english" in the class, and in the babel-package (and only English). Still the titles of my captions are "Abbildung" and "Tabelle" instead of "Figure" and "Table".  I didn't have this issue when using tuda-ci earlier this year, but I think there was an update concerning captions. I'm compiling with lualatex.

**Comment by schoeps** [comment]
Can you post a minimal working example, please?

**Comment by TeXhackse** [comment]
I guess you just load english as global option, you also need to change it with the babel package.

The difference is required, because the global option is also processed by other packages, but we need to set the main language for babel only. 

```
\usepackage[ngerman,main=english]{babel}
```

We automatically load the ngerman files, in case you are using the thesis in phd mode, because there are some parts enforced to be German.

**Comment by ATuda-ciUser** [comment]
Yes I actually used
\usepackage[english]{babel}, 
but with
\usepackage[ngerman,main=english]{babel}
it works.
Thanks!
