### ISSUE TITLE
tuda-pub does not build correct font with LuaLaTeX

### ISSUE THREAD

**Issue by PhRosenberger** [tudace/tuda_latex_templates#270]
Fonts are wrong and not bold when building the document with LuaLaTeX (as recommended), pdflatex does the job, but has other issues. Issue is connected to PDF/A mode, somehow.

Error message:
> Font shape TU/ptm/b/n' undefined(Font) usingTU/ptm/m/n' instead

It came with commit https://github.com/tudace/tuda_latex_templates/commit/a1ff6a8dff9c83220fe6263bfd7d581f06c63e82

To fix it, we simply add `\PassOptionsToPackage{T1}{tudafonts}` again in line 202 to get
```latex
%Option adjustments required for valid PDF/A
\bool_if:NT  \g_ptxcd_pdfa_bool {
  \PassOptionsToPackage{RGB}{xcolor}
  \PassOptionsToPackage{T1}{tudafonts}
}
```

**Comment by TeXhackse** [comment]
Could you please attach a log? The Type 1 enforcement could be removed with the roboto package providing all required metrics. So this might be caused by an outdated distribution.

**Comment by PhRosenberger** [comment]
> Could you please attach a log? The Type 1 enforcement could be removed with the roboto package providing all required metrics. So this might be caused by an outdated distribution or some leftovers of old tuda-templates using some weird fonts.

We are seing this on TUDa ShareLaTeX under https://sharelatex01.ca.hrz.tu-darmstadt.de/ldap/login.
So regarding the outdated distribution, there might be an update necessary by TUDa hrz?

**Comment by TeXhackse** [comment]
https://sharelatex01.ca.hrz.tu-darmstadt.de/4256636748yzwkmrbpwstc works fine for me and gives a valid pdf without the font shape message.

**Comment by PhRosenberger** [comment]
I only the the issue with LuaLaTeX, pdfLaTeX works fine, indeed. Can you confirm that both work on your side?

**Comment by TeXhackse** [comment]
The sharing link above is using LuaLaTeX. pdfLaTeX is using T1 font by default so couldn't give an issue. But the Font message you showed above doesn't look like a fontspec fontloader, so I assume you load some other package which is loading fontenc, which will disable the luaotfload mechanism. This is why I asked for a log file.

**Comment by PhRosenberger** [comment]
## Sry for the delay, here is our log-file, I hope you see the problem regarding the fonts there:
[output.log](https://github.com/tudace/tuda_latex_templates/files/5715329/output.log)

**Comment by TeXhackse** [comment]
Alright, it's your customization. The pifont package is switching back to the Postscript fonts. This is leading to the issue. (There might be others, because you load a plenty of packages afterwards.)

As you realized you can workaround by switching to Type1 font in general, but this is not a good option, because usually one would prefer the luaotfload-fontloader especially because there are no TeX specifig metrics in there. The Switching might probably work, but for further documents I'd suggest to adjust this.

Beside this you are also loading some packages which are not necessary, because we are based on KOMA-Script + some font modifications, e.g. you directly load the ptm family (Times). 

This issue is not caused by tuda-ci but by the fact you switch from a pdfLateX document to LuaLaTeX without adjusting the font setup. In case you need some support with these adjustments I can offer to help. I have access to the TUDa-Sharelatex via the account marei@peitex.de in case you want to share something.

This issue will be closed, because it's unrelated to tuda-ci.
