### ISSUE TITLE
Add script 'tuda-copy-template'

### ISSUE THREAD

**Issue by Grinzold** [tudace/tuda_latex_templates#282]
Please add a script, e.g.

  tuda-copy-template --template tuda-letter...

Or something like this, which copies the selected template.  This script should then also download the logo, or
offer the command line for downloading it.  For a letter it should also copy the lco-file with a hint about editing it.
And some hints that only 'pdflatex' works.  (Personally I use (old-school :) ) latex, dvips, pstopdf, which did not 
work.)

Otherwise, getting started is too difficult.  I know my way around using find, grep, dpkg... but the average 
users will not know this.

Maybe also a manpage?

**Comment by schoeps** [comment]
This repository is not supposed to be used for manual installation. We recommend a recent texlive or miktex distribution which readily ship with this package in the most recent version (or at least after few days due to the administrational overhead). 

Actually, I would rather try to make it  harder than easier to install the package manually... this is one lesson learnt from the old templates: too many students will mess up their latex installations (nonetheless, an explanation how to manually install the package is here: https://www.ce.tu-darmstadt.de/ce/latex_tuda/index.en.jsp).

> And some hints that only 'pdflatex' works.

I would formulate it more positively: everything (pdflatex, lualatex, xelatex) works but the (old-school) latex. If I recall correctly, we made that design decision at a very early stage to improve maintainability of the code. Actually, it maybe that some templates even work. Either case, I agree that this should be written somewhere in the manual/readme.

@TeXhackse: do we list somewhere which compilers work and which don't? (I fould just a remark somewhere that we recommend lualatex)

**Comment by Grinzold** [comment]
I didn't talk about installation.  I just use the texlive version coming with ubuntu/groovy.

Say, now I want to write a letter.  I need to know that the example letter is in /usr/share...  This is too messy for the normal user.

So, if you type 'tuda<tab>'  in a terminal and then see a list of commands, or just one command with switches, that e.g. copies everything needed for a letter into the current directory.  That is all. No installation.  Just copy the example files, gunzip them.  Give a hint about the lco-file for a letter.

Also the missing tuda_logo.pdf is a mess.  You just get the latex error message and it looks like a broken package.  There should be a huge info output: please download it from the URL... e.g. using 'wget https://...'.

Is it possible to use something like $HOME/.tuda-ci/ where the default logo and the default lco-file can go?

**Comment by schoeps** [comment]
> Say, now I want to write a letter. I need to know that the example letter is in /usr/share... This is too messy for the normal user.

Yes, this makes sense but this has nothing to do with this template. This workflow is the case for pretty much any template and any program (even Word). This is clearly up to the user to organize himself/herself? By the way: I also wrote exactly such a script for myself (but macOS, so not portable), which even queries address data from my address book and puts it at the correct spot in the tex-code. The zipped archive is mounted such that you can even modify the content without worrying to (un)zip. I use https://en.wikipedia.org/wiki/Archivemount.

> Also the missing tuda_logo.pdf is a mess. You just get the latex error message and it looks like a broken package. There should be a huge info output: please download it from the URL... e.g. using 'wget https://...'.

We are not allowed to ship the correct logo on request of the corresponding Dezernat. It requires a login on the web page, so we cannot automize it. By the way: if I recall correctly, the template should not give an error but a dummy picture if the image is missing. 

> Is it possible to use something like $HOME/.tuda-ci/ where the default logo and the default lco-file can go?

Yes, in your local latex tree. This is for me: `~/Library/texmf`

**Comment by Grinzold** [comment]
I am not writing for myself, I can find the included templates, make a script, keep my own tempaltes...

But the average user cannot.  These you need to help, I think.

**Comment by TeXhackse** [comment]
@schoeps We are only talking about the native PDF engines, because the requirement of PDF/A was set to default. If there is a request for latex on it's own it might become complicated. The Workflow via ps to pdf could be supported if this is required. But no, we don't explicitly write, that we currently don't have native for a DVI output. 

@Grinzold For this action so navigate through the directory structure there are the tools `texdoc` and  `kpsewhich` you can use kpsewhich to look for sources and texdoc to get the path of the doc and example files for a package. This is the recommended way, because every scripting beside this depends on the distribution itself. Since there are so many different possibilities to install TeX I would not recommend to add custom tools.

In case you are writing a letter more than once, you probably will use a copy of the default template and add your personal settings. Afterwards you will either copy this to an arbitrary location or to your localtexmftree and then can again use the tools to localize it.

**Comment by schoeps** [comment]
@TeXhackse No, I did not push for latex support, I'd rather like to document which engines are supported. I don't think that this is currently mentioned (e.g. a bullet list in the readme?)

**Comment by TeXhackse** [comment]
@schoeps Well, it's not about engines, rather about output formats… pdf/x only supports pdf of course. I'll make a suggestion.

**Comment by TeXhackse** [comment]
Returning to the actual topic @Grinzold I still don't get your point. And with 3.11 I added some information on pdf/a is not supported with dvi-output, so one has to disable that option.
