### ISSUE TITLE
Subtask formatting

### ISSUE THREAD

**Issue by StefanFabian** [tudace/tuda_latex_templates#286]
1. Is it possible to style the subtask design?
For example, in the old version of our exam, we used an itemize environment where (a), (b), etc. were positioned right next to the task description.

2. Is that possible to do with the new template?
Also, are there options to print a) instead of 1a), and to remove the bars?

3. Finally, would it be possible to do these changes only for specific subtasks (or all subtasks of one task but not for the subtasks of another task)?

**Comment by TeXhackse** [comment]
1. Yes. It's an environment created from a KOMA-Script sectioning command. A Standard-Itemize might be a bit difficult, because one would need a wrapper environment but archieving the Style is no Problem.

Do I get it right, that you want hanging labels, like one would have with an enumerate environment? 

2. I just realized, that tudaexercise currently does not support the ruledheaders option. But I think we should add this, because I don't like them anyway, the default was choosen to be compatible to some old LaTeX templates which have been spread. You can redefine the `\sectionlinesformat`, but I dont think most users will be able to do that.

```
\ExplSyntaxOn
\makeatletter
\renewcommand*\sectionlinesformat[4]{%
\parbox{\linewidth}{
	\@hangfrom{%
		\hskip #2#3}{
		\tl_if_eq:nnT {#1} {task} {
			\exp_args:No \tl_if_empty:nF {#4}
			{:~}
		}
		#4
		\tl_if_in:nnT {#1} {task} {
			\tl_if_empty:cTF{l_ptxcd_ex_#1_credit_tl}
			{\pointformat{\tl_use:c {l_ptxcd_ex_#1_points_int}}}
			{\creditformat{\tl_use:c {l_ptxcd_ex_#1_credit_tl}}}
		}
}}}
\makeatother
\ExplSyntaxOff
```
I will add support for tudapubs `ruledheaders` option. 

The Numbers can be changed by redefining `\subtaskformat`. It's default is:
```
\renewcommand*{\subtaskformat}{\thetask{}\thesubtask\enskip}
```

3. Of course. You can use grouping for your changes or add a similar structure, like another environment based on the definition of subtask.

**Comment by StefanFabian** [comment]
Thank you for the quick response!
> Do I get it right, that you want hanging labels, like one would have with an enumerate environment?

Yes, that is correct.

**Comment by TeXhackse** [comment]
I had a look via the sharelatex project, the adjustments are getting further than this. So I don't think we should get any further enhancement. Maybe only add the ruledheaders-option to remove theses from subtask. @marklaz @schoeps
