### ISSUE TITLE
Exercise/Exam obtain points

### ISSUE THREAD

**Issue by StefanFabian** [tudace/tuda_latex_templates#288]
Is it possible to obtain the points for a task or subtask somehow?
1. When you have a reference to the task?
2. By iterating the tasks somehow? (Not sure if that is possible with latex/Luatex)

**Comment by TeXhackse** [comment]
Everything is possible ;-) 

It's not directly supported, but one could do this of course by redefining `\pointformat` or `\creditformat`.
But it might be difficult without some basic knowledge of macro creation. 

Since you have a bunch of small issues concerning the customization I'd suggest we share a sharelatex project via the TUDa Instance (my account there is marei@peitex.de) to have a look at this and I will choose which features might be useful for TUDa-CI in general.

**Comment by StefanFabian** [comment]
Hm, that sounds quite hacky ^^
I guess I'll just take the lame route of specifying it manually at the start and using a lua fueled command to look it up for each exercise.
What do you suggest to put in the sharelatex project?
I can strip the exam of any information and put it there but it doesn't show how it is supposed to look in the mentioned aspects.

**Comment by TeXhackse** [comment]
Replace text by random letters,  graphics can simply be left out by `\PassOptionsToPackage{demo}{graphicx}`.
I don't know the content so I cant tell you what you need to show - You don't have to enable link sharing, personal share would be enough since I have an intern account anyway. 

And it depends where you want to reference the points. If you want to reference before you define the tasks, you'd have to write the data to the aux file anyway. It's not really hacky, but a bit LaTeX specific kind of coding.

**Comment by StefanFabian** [comment]
I mean it sounds quite hacky to redefine the pointformat or creditformat command for that since in general I have no way of knowing which one if any is used.
I've invited you to a sharelatex project.

This also brought up the idea that the points for a task could be computed from the points of each subtask.
That would make it less error-prone.

**Comment by TeXhackse** [comment]
Alright, I'll have a look

**Comment by TeXhackse** [comment]
@schoeps @marklaz 
I am not sure you would like this enhancement as a generally feature with tudaexercise:

Current suggestion:
- Add an auto mode for the points.
- If there are subtasks the number of points for a task are the sum of all subtasks inside the environment. 
- Otherwise the points are added directly for the task environment 
- one could reference these values by `\getTaskPoints{<Number>}` or `\getTotalPoints`

**Comment by schoeps** [comment]
This seems to be a more popular problem (and less easy to make work on your own) in compare to the other issue, so I guess I would be in favor to add this but I have no strong opinion. @marklaz?

**Comment by melhindi** [comment]
At our group we would really value an auto mode for points.
Especially, if an exam contains many subtasks that are changed regularly during exam creation, it is time-consuming and error-prone to manually adjust points.
I like the suggestion of summing up points and making them available via `\getTaskPoints{<Number>}` or `\getTotalPoints` commands.

**Comment by melhindi** [comment]
I would also vote for having a standard mechanism to create an exam cover-sheet (incl. table for points) - kind of re-opening #203.

**Comment by TeXhackse** [comment]
I just received the info it's okay if I add this. Will be rolled out during the next days.

**Comment by TeXhackse** [comment]
Das feature ist jetzt fertig implementiert und getestet. Ich bereite jetzt noch ein paar weitere kleine Ergänzungen vor, dann sollte der Release heute noch rausgehen. Es ist dann Bestandteil von TexLive 2021, dass diese Woche erscheint.
