### ISSUE TITLE
Linebreak for TUprints in dissertation layout

### ISSUE THREAD

**Issue by AndiTaubel** [tudace/tuda_latex_templates#289]
Hello together,

I have a question concerning the phd thesis layout of the latex template. On the second page of the cover information, the details for the publication over tuprints are implemented by the command 

\tuprints{urn=123456, printid=12345, license=cc-by}

In the document that produces the URN and URL information in one line even without a space in between. Is there a way to separate this to have a linebreak between "URN: urn:nbn:de:tuda-tuprints-123456" and "URL: http://tuprints.ulb.tu-darmstadt.de/12345"?

I am very grateful for your help!

Best Regards
Andreas

**Comment by TeXhackse** [comment]
Hi Andreas,
thanks for reporting. We had a bug concerning this which was fixed long time ago. 

Could you please ensure you are not using an outdated version of tuda-ci?

You should find that information in the logfile, there should be a linebreak between urn and url info.
If your version number is <3.10 (current version is 3.11) you should try to update. 

In case you don't know how to do this, please give us more information on your OS/TeX distrbution, then we can try to help.

Thank you
Marei

**Comment by AndiTaubel** [comment]
Hey Marei,

thanks for the reply. I am using version 2.09 (2020/03/09), since this was the newest when I started writing my thesis. I am using the Texmaker over Miktex on windows 10. Is there an easy way to implement the newest version without messing up all other formating of the document?

Best Regards
Andreas

**Comment by TeXhackse** [comment]
Hi Andreas,
if you have clean code structure this would not mess up anything if you update.  Because the formating is done by tuda-ci. If you added a lot of manual tinkering this might cause issues (but you should not do that anyway).

You can test it by downloading the zip from the release section and place the used files in the working directory. 
In case this is messing anything up you could also overwrite the definition of the `\lowertitleback` variable. 

Then you can decide to update or install the current version locally.

**Comment by AndiTaubel** [comment]
The implementation of my document into the newest version of the template worked fine. Thank you very much for your time and your support and for solving my problem immediately =)

Best Regards
Andreas
