### ISSUE TITLE
Math fonts

### ISSUE THREAD

**Issue by pfetsch** [tudace/tuda_latex_templates#30]
In the beamer version, the math fonts use serifs and are too small. I recommend to change the math font to some font similar to helvetica.

I am not sure whether the same problem appears in the other classes.

**Comment by TeXhackse** [comment]
## Default math font

> Beamer allows to use sans serif via the font theme themes/font/beamerfontthemeserif.sty.

This is not true. This theme allows you to set the default to serif fonts. The sans serif is usually the dafault. I fixed the bug, which was disabling font mixing, as it's default in beamer. So the default is now the same setup as beamer would provide.

I now implemented an serif Option similar to the old template, which would load the serif font theme and not set the default family to `\sfdefault`.

## Sans serif math
Problem with math fonts here is the same as mentioned in #19. Especially for sans serif.
Therefore I'd suggest the following setup with lualatex:

```
\setmathfont{Fira Math}
\setmathfont[range=up]{Roboto}
\setmathfont[range=it]{Roboto-Italic}
\setmathfont[range=\int]{Fira Math}
```
Since it's compiler dependent I'd suggest to add a note on that to the documentation and would not enable it by default. But it would take the Roboto letters and use the sans serif Symbols from Fira Math.

## Resizing Math Fonts
The base fontsize is equal to the text font. This size is usually large enough. You could either use the beamer Options `11pt`/`larger` or even `12pt` to increase the fontsize in general.

Beside this, if you only want to increase the math fonts, it's possible to adjust the MathSizes, the default setting in readible variant is:
```
\DeclareMathSizes{10}{10}{7}{5}
```
So for a fontsize of 10pt the math base font will also be sized to 10, scripsize is 7 and scripscriptsize is 5. This default setting can be found in `kpsewhich fontmath.ltx`
(usually something like texlive-root-dir/2019/texmf-dist/tex/latex/base/fontmath.ltx)

I hope this information helps out.

**Comment by pfetsch** [comment]
This looks good now - thank you. I recommend to add a math formula in the demos, though.

**Comment by TeXhackse** [comment]
I leave it open until the math demo is added. thank you

**Comment by TeXhackse** [comment]
I know. This is only telling you that Roboto is not supporting math spacing itself. It's not a good option at all. Best would be to have a matching math font, but we dont.
