### ISSUE TITLE
improve compatibility of tudaexercise.cls (from TUDa-CI v3.13a) with TeX Live 2019

### ISSUE THREAD

**Issue by ma137** [tudace/tuda_latex_templates#301]
`DEMO-TUDaExercise.tex` in combination with TUDa-CI v3.13a does not successfully compile under TeX Live 2019, while it does so under TeX Live 2020. The cause seems to be the command `\prop_gput:Nxx`, which is used in `tudaexercise.cls`. It looks like this command is not defined in TeX Live 2019. 

This problem can be fixed by inserting `\cs_generate_variant:Nn \prop_gput:Nnn { Nxx }` in `tudaexercise.cls` (e.g., directly after the line `\RequirePackage{l3keys2e}`). According to my understanding of the [expl3 documentation](http://mirrors.ctan.org/macros/latex/contrib/l3kernel/interface3.pdf) this supplementation should not have any effects under TeX Live 2020, where `\prop_gput:Nxx` seems to be already defined.

So, adding this line seems to be a nice way of increasing the compatibility of `tudaexercise.cls` (of TUDa-CI v3.13a) with older TeX Live versions.

**Comment by TeXhackse** [comment]
@ma137 thanks for the hint. I added TL2019 to the testing mechanism and will include a change on this in the next release. I will not add an extra variant for this only use of the mechanism, but expand the arguments directly if the variant is missing. 

Since this only affects manual installs anyway I'd not prepare an extra release for this. Until then users can use your workaround by inserting
```
\ExplSyntaxOn
\cs_generate_variant:Nn \prop_gput:Nnn { Nxx }
\ExplSyntaxOff
```
before \documentclass.


This is only due to the fact, that I should not modify a module which is not ptxcd inside the class.

**Comment by ma137** [comment]
Thanks for the fast and detailed answer! Your strategy sounds good to me.

**Comment by TeXhackse** [comment]
Um, could it be, that you manually adjust some things about this? 

```
\csname ptxcd_thesisType\endcsnam \text{ }
```

is not included in TUDa-CI and the `\endcsname` is missing it's last letter. (+ The `\text{ }`  ist a weird construction there I'd not use it that way.

**Comment by TeXhackse** [comment]
TL19 required some more adjustments, but it seems to be fine now. @ma137 would you mind to have a try? I have a plain TL2019 and one with the freezed status for testing, but some linux packages require more than that. 

Please pay attention to the fact, that the `points=true/auto` mechanism won't work in TL19. because the implementation would require a much higher effort.

**Comment by ma137** [comment]
@TeXhackse Thanks for informing me!

So, do I understand you correctly, that it should work under TL19 by using `points=false` with the exception that `\refPoints`, `getPoints` etc. from `DEMO-TUDaExercise.tex` can cause problems?

So I tried to compile `DEMO-TUDaExercise.tex` using pdfLaTeX under Ubuntu 20.04 with TL19 as provided by the Ubuntu packages. Independently of the used value for the `points` option, I get the following error message:
```
! Undefined control sequence.
<argument> \exp_args:NNxx 
                          \prop_gput:Nnn 
l.74 \begin{task}{Titelei}
```

If insert 
```
\ExplSyntaxOn
\cs_generate_variant:Nn \prop_gput:Nnn { Nxx }
\ExplSyntaxOff
```
before `\documentclass`, everything works as expected. (`points=true` seems to work.) If I understand [this commit](https://github.com/tudace/tuda_latex_templates/commit/f2602546cf79b2f0fedcffa545c912d7b9456452) correctly, this works because in this case the function `\exp_args:NNxx`, which seems not to be available on my installation, is not called.

**Comment by ma137** [comment]
@TeXhackse Maybe, one could use GitHub Actions to automatically test if the example documents compile successfully under Ubuntu 20.04 etc.?

I created a simple proof of concept: I forked the repository and added a config for GitHub Actions. The config can be found [here](https://github.com/ma137/tuda_latex_templates/blob/master/.github/workflows/tests.yml) and 
[here](https://github.com/ma137/tuda_latex_templates/runs/2579006883?check_suite_focus=true) is the output of an automatic test executed via GitHub Actions after a commit. 

It shows that compiling the report example works currently under Ubuntu 20.04, while compiling the exercise example does not work. (Because of using `points=false`, which is inserted by a `sed` command, it wouldn't compile without errors anyway, but the error here is not because of that as can be seen from the output.)

**Comment by TeXhackse** [comment]
I know how to set up a CI, But I don't want to that for all custom setups. 

The problem is, I can run tests on every system, but the effort will not be worth it, that's why I usually focus on the official TeX Live releases. The one made with the TeX Collection + the final update state when the version is freezed at the end of the year in preparation for a new TeX Collection. 

The Linux Distributions differ a lil bit. everyone is like doing their own stuff and taking the update status from the moment packaged. For testing this would mean I'd have to use an outdated state of every day of the last years… which is not really possible. That's why I usually encourage people to update. Actually I just started this, because it seemed to be no big deal to regenerate compatibility … Thing is, If i add a lot mechanisms as fallbacks this will blew up the code. So I have decide what's okay to be supported and which one not. 

But it seems like TL 2019 is a bit special once again for Ubuntu, so since I already started I will start a VM setup… Thanks anyway

**Comment by TeXhackse** [comment]
@ma137 I tested it and I can compile it on a freshly installed Ubuntu 20.04 with a TeXlive from the default repository. 

The installation is a bit weird anyway, because I get a format file which is dated 2020-02-02 but it states TL 2019 and loads some expl3 things from 2021. Log file attached.  I can offer to compare your log to mine but since I installed nothing beside the texlive packages + the current version of tuda-ci it works fine it seems like being a problem of your local installation and not Ubuntu 20.04.

[debian20-vm-demo-exercise.log](https://github.com/tudace/tuda_latex_templates/files/6479356/debian20-vm-demo-exercise.log)

**Comment by ma137** [comment]
@TeXhackse Thanks for the detailed information and the log file. Maybe I have found the difference: You used `lualatex` for compiling, while I used `pdflatex`. If I use `lualatex`, it works, but with `pdflatex` I get the previously mentioned error related to `\exp_args:NNxx`

The [output of this GitHub Action workflow run](https://github.com/ma137/tuda_latex_templates/runs/2590719439?check_suite_focus=true) contains the information on the used setup as well as the output of `pdflatex` and `lualatex`.

I understand that it might not be worthwile to explicitly support many Linux distributions and test against them. Furthermore, I understand that too much backwards compatibility can largely decrease maintainability and can have other downsides. 

In this context, it is not fully clear to me which TUDa-CI version should work with which Tex Live versions. Maybe I have overlooked these information. I have read in the documentation that it is recommended to install TUDa-CI from TeX distributions such as Tex Live. It is also explained that updates can be done by installing all available updates for the distribution. I guess that by following this procedure the compatibility between TUDa-CI and its dependencies is ensured. However, in my experience users sometimes update TUDa-CI by obtaining a new version of the package from GitHub/CTAN without updating their TeX distribution, sometimes because this distributions is installed from Linux package sources. Not wanting to update other packages from the TeX distribution might be a another reason. Just in case you are already testing TUDa-CI with Tex Live 2019, could you provide somewhere some information about the compatibility or incompatibility of the current TUDa-CI version with the Tex Live version you tested it with?

**Comment by TeXhackse** [comment]
I see I was expecting it to be a general error and not pdflatex only. I will have another look. 

> In this context, it is not fully clear to me which TUDa-CI version should work with which Tex Live versions. 

Generally speaking: tuda-ci works with the TeX Live installation it's part of. That's what you can expect.
I usually test the current + the last release to allow the users a lil bit of flexibility, which is currently TL2021 and TL2020.

So you can use the current TUDa-CI relase with the current TeX Live release. 
Because we depend on other packages that's the most useful way of handling this.

You still can use the TUDa-CI variant which is included in the debian package. You can compare this to a basic software and addons, usually you don't request an addon of a newer version to be compatible to the older version of the software. 
So if you want to use the debian package I expect users to use the outdated variant provided there or update all required packages. 

Beside this all linux packages slightly differ. Because they are built and updated independently from the official TL release. Therefore I always recommend users if they want to use the most recent developtments of TeX Live to use the ctan based installation using tlmgr. 

I hope this helps. Anyway since I was missunderstanding your original request and already started to add soome compat things it will now be running on tl2019.

**Comment by ma137** [comment]
With your latest commits it works on my system as expected. Thanks for this and the information.
