### ISSUE TITLE
texmaker error when referencing the date of submission

### ISSUE THREAD

**Issue by 1lyass** [tudace/tuda_latex_templates#302]
Hello,

the date of submission doesnt show up in the pdf file after i compile with lualatex in texmaker. There also isnt a LOG-file in my latex folder that i can attach so i made a screenshot.

Best regards  

![Screenshot (21)_LI](https://user-images.githubusercontent.com/75802671/113359652-839d8900-9348-11eb-8de2-c04dca19026f.jpg)

**Comment by TeXhackse** [comment]
Is there a DEMO-TUDaThesis file (with hidden ending) in your working directory? If there is this one is the logfile you can check this by right-clicking showing the properties.

(Windows is hiding the extensions for „known“ filetypes by default).

Without more information it's a bit difficult to say, because you are showing a code-snipped using `\text{ }`and `\authors`which I do not define.

**Comment by 1lyass** [comment]
Yes there is. I found it now.
[DEMO-TUDaThesis.log](https://github.com/tudace/tuda_latex_templates/files/6248773/DEMO-TUDaThesis.log)

**Comment by TeXhackse** [comment]
Um, could it be, that you manually adjust some things about this? 

```
\csname ptxcd_thesisType\endcsnam \text{ }
```

is not included in TUDa-CI and the `\endcsname` (`\endcsnam` should be changed to `\endcsname`) is missing it's last letter. (+ The `\text{ }`  ist a weird construction there I'd not use it that way.


Beside this, this is not a texmaker error, it's a LaTeX error. TeXmaker is only the editor reading the error file and showing you the most important parts of this ti make it easier for you to understand.

**Comment by 1lyass** [comment]
No i didnt adjust things, my institution where i write my thesis did this. But now the error doesnt show up anymore.
Thank you for your help

**Comment by TeXhackse** [comment]
Then please Tell them about it. We are not responsible for their bugs and can't fix them.

**Comment by 1lyass** [comment]
i told them but i have to figure it out on my own. 
Thank you for your help and time.

**Comment by TeXhackse** [comment]
That's totally okay. I'd just like them to fix it in their template. If possible I can also can get into contact, and explain to them why \text is overpowered for that usecase. So If it's possible tell them to contact me, please. Would be a lot less issue for me instead of always telling people to fix it in their own.
