### ISSUE TITLE
Presentations: Handout mode

### ISSUE THREAD

**Issue by unp1** [tudace/tuda_latex_templates#304]
Dear all,
  when I try to activate the "handout" (\documentclass[handout] ... ) mode for beamer presentations, it corrupts the layout of the slides, i.e. the content of some boxes is moved out of the pdf page, background color/boxes disappear etc.

Am I doing something wrong?

I added a small example to this issue.
[standalone.zip](https://github.com/tudace/tuda_latex_templates/files/6310673/standalone.zip)

Thanks a lot and best regards, 
Richard

**Comment by TeXhackse** [comment]
Hi Richard,
thanks for reporting. This seems to be a bug in the option passing. I will have a look at this during the next days. Because I don't want to break some other modes during this.

You can currently use a workaround by adding 

```
\makeatletter
\gdef\beamer@currentmode{handout}
\makeatother
```
instead of the handout option.  right before `\begin{document}`

If you need anything else, feel free to ask.

Marei

**Comment by unp1** [comment]
Hi Marei,

  thanks a lot for looking into it and in particular for the workaround. It works great now and saves me some tedious manual work :-)

Best regards, 
Richard
