### ISSUE TITLE
Lines above and below a section and subsection titel  (Custom Mod not related to this Repo)

### ISSUE THREAD

**Issue by 1lyass** [tudace/tuda_latex_templates#305]
Hello,

how can i put lines above and below a section and subsection titel? 

I used this code but it doesnt work the way i want it to be:

**\usepackage{titlesec}
\titleformat{\section}[block]
  {\titlerule\addvspace{4pt}\normalfont\fontsize{14}{16}\bfseries}
  {\thesection\enspace}{0pt}{}[\vspace{2pt}\titlerule]**

Here is a example how i want the lines to be:

![grafik](https://user-images.githubusercontent.com/75802671/114912674-90c67780-9e20-11eb-8b6e-93e85cd6fb58.png)

Best regards

**Comment by schoeps** [comment]
What about `ruledheaders`?

https://github.com/tudace/tuda_latex_templates/blob/7607d370c727a924bd27de3854872b95f1e1720a/example/DEMO-TUDaPub.tex#L102

**Comment by TeXhackse** [comment]
`ruledheaders=all` is the default setting. So I guess the loading of titlesec killed the whole setup concerning this.

You should not load titlesec and in case you have another value of `ruledheaders` you should remove that one.

**Comment by 1lyass** [comment]
Thank you for your fast response. I deleted the code. Its normal now but without lines. The ruledheaders=all is already in my documentclass which has the same input of the original template you developed. Is there a better code to draw the lines?

**Comment by TeXhackse** [comment]
Did you try to compile the original Version of DEMO-TUDaPub.tex? (If you don't know where to find it on your system, you can also take this one: http://mirrors.ctan.org/macros/latex/contrib/tuda-ci/example/DEMO-TUDaPub.tex)

**Comment by TeXhackse** [comment]
And I mean your template might do some changes elsewhere which have an impact on this. I cannot say anything more without knowing the code you are using. So I suggest you compile our DEMO-file and if this one is working we know that they changed something about it. 

You still can send me template and I can have a look but since you told us you shall use this template I'd prefer to get into contact with the people who made it. There will be other people facing the same issues.

**Comment by 1lyass** [comment]
Here is the template. I dont know why **ruledheaders=all** doesnt work. I found this contact in the files: **menner@fsr.tu-darmstadt.de** 

[FSR-Latex-Vorlage_2020.zip](https://github.com/tudace/tuda_latex_templates/files/6320458/FSR-Latex-Vorlage_2020.zip)

**Comment by schoeps** [comment]
@TeXhackse I don't think we should debug the templates of other groups... 

@1lyass please ask your supervisor at FSR. If they supply the template than they should also make sure that it fulfills their (?) rules.

**Comment by TeXhackse** [comment]
@schoeps  I'd not do that. But the file "Einstellungen/Settings.tex" ist overwriting my setup. 
They are based on an outdated version of TUDa-CI. So they are using internal macros which got changed some versions ago already.

So @1lyass as I said before their template is broken and doesn't support our feature. But now I can be sure it's not my fault. I can inform the author of the fact it doesn't compile (it even throws error with the current Version of TUDa-CI because the author is using some dropped internal macros.)

**Comment by TeXhackse** [comment]
Since I ensured now that this issue is not related to TUDa-CI I will close this issue as unrelated.
I'll send an email to the author linking this issue.
