### ISSUE TITLE
Unable to compile after recent TeX Live Update (pdfa=true)

### ISSUE THREAD

**Issue by maxkratz** [tudace/tuda_latex_templates#321]
Hi all,

I've encountered some problems while trying to compile my thesis (with the TUDa LaTeX template) on the [ShareLaTeX instance of TU Darmstadt](https://sharelatex01.ca.hrz.tu-darmstadt.de/). Everything compiles fine on my workstations which uses `TeX Live 2019/Debian`. I then created a new ShareLaTeX project that uses the [DEMO-TUDaThesis.tex](https://github.com/tudace/tuda_latex_templates/blob/27ccc7cff0cc41b585779ce708857af068799269/example/DEMO-TUDaThesis.tex) file from the [latest release (3.16)](https://github.com/tudace/tuda_latex_templates/releases/tag/v3.16), set the compiler to 'LuaLaTeX' and the main document to 'DEMO-TUDaThesis.tex'.

Unfortunately, the example thesis **does not compile on the ShareLaTeX instance**, too.
First shown error:
```
No \begin{document} command was found. Make sure you have included \begin{document} in your preamble, and that your main document is set correctly.
```

The said instance uses texlive 2021, as I can see from the generated log output. Is this related to a problem of the ShareLaTeX instance or is the thesis template incompatible with the latest texlive version?

Log of the compilation process: 
[output.log](https://github.com/tudace/tuda_latex_templates/files/6758095/output.log)

Best regards
Max Kratz

**Comment by TeXhackse** [comment]
Hi,
they added a latexmkrc which will always break if there's error.

The error seems to be a bug with the pdfa-mode. I will have a look at that.
As a workaround you can disable the pdfa-mode by adding `pdfa=false` to the `\documentclass` options. 

Please pay attention that you also will have to remove the `\Metadata`macro because it doesn't exist with pdfa turned off.

I will information as soon as I found the reason for this.

**Comment by maxkratz** [comment]
@TeXhackse Thank you for the quick reply and your help :smile:. `pdfa=false` together with removing the content of `\Metadata` did the job as a workaround.

**Comment by open711** [comment]
After two hours of trouble shooting today I luckily had a look in here. My thesis wouldn't compile after an update of babel and the package "latex-firstaid", that I have never heard of. 
pdfa=false with removing the content of \Metadata also worked for me.

**Comment by TeXhackse** [comment]
@open711 thanks for the additional info, I am already talking to the maintainer of pdfx and we are working on that. latex-firstaid is a package developed by the LaTeX-3-development-Team to workaround internal bugs with the current changes in the Kernel. It's automatically loaded if required, but maintainers are encouraged to fix these issues themself.

**Comment by TeXhackse** [comment]
With the current available latex-dev it's working again, so I am optimistic it will be resolved fast.

#### In case it's urgent

With a installation including the TeX Live manager one can install the dev-formats which don't have the error anymore.

```
tlmgr install latex-base-dev lualatex-dev
```

Afterwards you are able to run lualatex-dev instead of lualatex onto your file. 

If you need help with this, please let me know.

**Comment by TeXhackse** [comment]
There's an update of pdfx in preparation, I will let you know when it's released to get your systems udpated.

**Comment by AxelFrotscher** [comment]
Maybe for the people in a hurry, who have an updated version of TexLive2021 on Mac I think I found a solution (tested on M1 MacBook Air). I did not run the specialised tlmgr command from the previous post.
In the ~/Library/TexShop/Engines folder, there are the available engines listed. To use lualatex-dev, it is enough to move the file "LuaLaTex-dev.engine" from ~/Library/TexShop/Engines/Inactive/LaTex "dev" versions/ to ~/Library/TexShop/Engines, and then restart TexShop, and select LuaLaTex-dev. Then I could mitigate the error.

**Comment by TeXhackse** [comment]
That's what I meant with the dev format. But thanks for the explicit hint. Didn't know TeXshop has his feature inside the gui.

**Comment by TeXhackse** [comment]
Since I didn't receive any further information I added a dirty hack to workaround the issue. It's added with todays release and will be removed as soon as possible. Since I cannot promise it will not cause any other issues it should be handled with care and throws a warning to inform users to only use pdfa=true if this is enforced. 

I will keep this issue open until we have a final solution.

**Comment by mischw** [comment]
I will soon have to submit my thesis in PDF/A. Can you narrow down what kind of issues I should look out for when using this workaround? Any ETA for a long term fix? Thanks

**Comment by TeXhackse** [comment]
The workaround works. You can compile with the latest update(two weeks ago). So for a user it should seem “fixed”. It's just an ugly “solution” until the other issues are resolved.
