### ISSUE TITLE
Reduce margins TUDaThesis

### ISSUE THREAD

**Issue by Annemike** [tudace/tuda_latex_templates#334]
I noted, that the spacing in the Overleaf template of TUDaThesis is too big on both the upper and the lower side of the page. 
![Screenshot 2021-08-23 at 16 43 35](https://user-images.githubusercontent.com/11015831/130467320-452923f3-be5c-4bf1-81fd-da9bd6ed8124.png)

**Comment by TeXhackse** [comment]
There is no official Overleaf template due to Trademark restrictions we may not publish it there.
TUDa's local instance (sharelatex01.ca.hrz.tu-darmstadt.de/) has the latest version.

Anyway:
The margins are fine that way they are calculated using the typearea package. If you want to stick to the official margins you can remove the `custommargins=true` option. That setup is leading to ultra small margins.

For custom setup set `custommargins=geometry` and use `\geometry{}`with the options described in the geometry documentation to adjust the settings.

**Comment by TeXhackse** [comment]
I will close this one because it seems resolved to me.
