### ISSUE TITLE
tudaposter author not displayed

### ISSUE THREAD

**Issue by ChristophReich1996** [tudace/tuda_latex_templates#335]
Hey, I have the problem, if I set `\author{Christoph}` no author appears on the poster. Is there any possible solution or am I doing something wrong?

**Comment by TeXhackse** [comment]
No, you are not doing anything wrong.

It seems like we did not think about where an author should be displayed and forgot that one. 
TUDaposter is intended to be used for announcement posters which typically don't have an author. But it's a bit weird, because I set it myself in the template. Will fix that.

**Comment by TeXhackse** [comment]
@schoeps @marklaz I'd place it similar to the tudapub titlepage, I guess that's the best option. Any offense?

**Comment by TeXhackse** [comment]
@ChristophReich1996 Since I am not sure if you really want to use TUDaPoster, please pay attention to the fact that there's also TUDaSciposter for scientific posters. Maybe that fits your usecase better than this one.

**Comment by schoeps** [comment]
> @schoeps @marklaz I'd place it similar to the tudapub titlepage, I guess that's the best option. Any offense?

Sounds good to me!
