### ISSUE TITLE
long subject overlaps sidebar in tudaletter

### ISSUE THREAD

**Issue by Kjili** [tudace/tuda_latex_templates#348]
Hello,

I am currently using tudaletter and noticed a problem with long subjects and/or titles, as they overlap the sidebar with institution, logo etc. I think this is because linewidth - at this position - still refers to the whole page and not the whole page minus the sidebar.

I came across this problem when trying to center text in my letter, as I have to use both a centered subject or title and will also have to work with very long subjects (more than one line). Centering in the body works with `\makebox[\linewidth][c]{my centered text}` (the center environment does not work). However, I have not found any simple solution to center the subject or title, as it is always centered on the whole page regardless of using the above command or `\KOMAoption{subject}{centered}` or similar. As far as I can tell makebox would work if the linewidth were the same as in the body.

Minimum working example that demonstrates the problem:
```\documentclass[]{tudaletter}
\begin{document}
\begin{letter}{%
    Technische Universität Darmstadt\\%
    Referat Kommunikation\\%
    Karolinenplatz 5\\%
    64289 Darmstadt}
\setkomavar{frominstitution}{my institute}
\setkomavar{subject}{A very long sentence following it to demonstrate the problem of overlapping the sidebar\\\\This is even more extreme when entering a (perhaps not so nice) forced newline that contains an even longer sentence or (in my reference letter) the usually very long name of a thesis as a subtitle, in which case it actually overlaps the institution name}
\opening{}
\end{letter}
\end{document}
```

**Comment by TeXhackse** [comment]
The subject does not expect a text which includes more than 3 lines. But you're right in the example this would happen. 
The layout itself want's the subject line to span across the full \textwidth, but we can add an option to support it. 
@schoeps @marklaz do you think that should be done?

The width of the text without the sidebar can be accessed as
```
\dim_eval:n {\c_ptxcd_Linewidth_dim + \c__ptxcd_firstpage_extraindent_dim}
```
So as a workaround one would set the subject into a parbox of this width. Acessing it in l2 syntax can be done by adding 
```
\ExplSyntaxOn
\newcommand\textwitdhwithoutsidebar{\dim_eval:n {\c_ptxcd_Linewidth_dim + \c__ptxcd_firstpage_extraindent_dim}}
\ExplSyntaxOff
```
to the preamble. And then surroundt the subject by a parbox of `\textwitdhwithoutsidebar`.

Concerning the centering inside the body does not work at all because the implementation of the linewidths adjustment is quite complicated. We could support the alignment environments, but if possible it's much more stable to box these or disable the automatism to automatically detect the change of linewidths within a pagraph.

**Comment by TeXhackse** [comment]
Alright so the document type is not really a letter and it's not really a subject. 
I'd suggest to not use the subject in this case but adjust the vertical spacing so the text will start earlier than it currently does including a box for this title variant. 

The word template (at least the version I had when we started developing this= sadly does not really match the requirements of the CD guideline because the basic issue is that the line length should change even withing a paragraph. Within Word this is simply resolved by adding a hard pagebreak or not doing this adjustments. Therefore it's working completely different. There also were some spacing issues we had adjusted everything to match the official guideline instead of the word template due to these. 

I can also offer to mail me the current syntax and a word example and I will have a look if it might be useful to add a custom config for documents of this type. TUDa-CI is extendable in that way.

**Comment by Kjili** [comment]
Ah okay, I wasn't aware of the word and CD issues.

> Alright so the document type is not really a letter and it's not really a subject.

It's probably something in between. It has all the letter formatting (that are only indicated by placeholders in the reference, with the backadress and from, even the fold markers), but it does not have the usual opening and closing. In any case, the tudaletter template covers what I need pretty well, definitely worth using even if it is a bit different than the default letter.

> I'd suggest to not use the subject in this case but adjust the vertical spacing so the text will start earlier than it currently does including a box for this title variant.
> I can also offer to mail me the current syntax and a word example and I will have a look if it might be useful to add a custom config for documents of this type. TUDa-CI is extendable in that way.

I think I'll go with the custom spacing and box for now, as it's the simplest solution. I have not yet had any other subjects like this, so maybe this is a rare issue. Thank you for the super-quick help and happy holidays!

**Comment by schoeps** [comment]
> The subject does not expect a text which includes more than 3 lines. But you're right in the example this would happen. The layout itself want's the subject line to span across the full \textwidth, but we can add an option to support it. @schoeps @marklaz do you think that should be done?

I think this should be at least fixed if `narrow=true` is set. This is anyway not fully compatible with TUDa-CI (but is used by many colleagues).

**Comment by TeXhackse** [comment]
@schoeps you mean `refline=narrow`?

**Comment by schoeps** [comment]
True, I was confused. Did we use `narrow=true` at some point? Either way, it works fine on my machine if `textwidth=narrow` is set, so I don't think we need to change anything. 

@Kjili is `textwidth=narrow`working for you?

**Comment by TeXhackse** [comment]
`narrow=true` is not an option neither for scrletter nor for tudaletter. That's why I asked. 

`textwidth=narrow` is switching off the adjustment of the linewidth after the first page. That's what I meant when I was talking about „disable the mechanism“. 

It's automatically active for the `department=mecheng`.

**Comment by schoeps** [comment]
> `textwidth=narrow` is switching off the adjustment of the linewidth after the first page.
 
...and it also fixes the subject line. That was my point. I'd say this is good enough. We should not maintain to many options that are violating the TUDa-CI. See how I confuse the options and imagine how it will be for normal users ;)

**Comment by TeXhackse** [comment]
fine with that.

**Comment by Kjili** [comment]
@schoeps Yes, `textwidth=narrow` works for me, thanks! I wasn't aware that it also influences the first page.

**Comment by TeXhackse** [comment]
I should probably improve the documentation on that.
