### ISSUE TITLE
Monospaced numbering as default for Review/Gutachter?

### ISSUE THREAD

**Issue by RisingNeon** [tudace/tuda_latex_templates#352]
Maybe this is not so important for everyone but multiple reviewers are not aligned properly.
![grafik](https://user-images.githubusercontent.com/24548767/151156574-35ebcce9-d6e3-4b49-9cea-b56a6d76e9bb.png)
I think the issue here is that the numbering is not in a monospaced font which shifts at least the first reviewer to the left.

A possible fix is using _\setupReviewName[1]{\texttt{1}. Review}_ which looks fine to me. So everything is alright but I still want to point out this problem and suggest a change of the default if this is deemed to be important.

**Comment by TeXhackse** [comment]
A change to a monospace font there is not a good idea at all, but you are right concerning the alignment, it's not perfect.

I suggest to change the local default to lining numbers instead for the next release. We generally did not add additionall alignment because a lot of users require different naming scheme instead of the numbers.
