### ISSUE TITLE
Overriding the current tuda versions in Overleaf/ShareLatex

### ISSUE THREAD

**Issue by ercan-akar** [tudace/tuda_latex_templates#360]
Hi together, 

I've noticed that the templates in Overleaf are old and the tuda packet version. I have not seen a guide or question about it; I just wanted to share my experience. You can always use the newest or your favorite version like this:

1- Upload the tex folder to your main project folder
2- Create an empty file "latexmkrc"
3- Add this line to latexmkrc:

 $ENV{'TEXINPUTS'}='./tex//:' . $ENV{'TEXINPUTS'};

4- Now Overleaf and Sharelatex check the first "tex" folder for styles

**Comment by TeXhackse** [comment]
Overleaf cannot be officially supported because we may not upload the logo files there. 

TUDa Sharelatex should be updated and also has the logo files isntalled. If not please contact the support over there. 

Anyway just to add a TeXnical comment. One should use the `ensure_path` subroutine described in the latexmk documentation. And … like we do it in the latexmkrc provided inside this repo ;-)
