### ISSUE TITLE
uppertitleback with "twoside = false" 

### ISSUE THREAD

**Issue by schrchr** [tudace/tuda_latex_templates#37]
Is it possible to get "uppertitleback" for a Master thesis, while having "twoside = false" and not using "\tuprints{...}"?

**Comment by TeXhackse** [comment]
The basis idea of an uppertitleback does not exist if twoside=false. It is the back of the titlepage, which will stay blank on onesided documents.

What is the intention behind this?
It would be possible to add data in a similar way, though the concept of uppertitleback does not make any sense in this context.

**Comment by schrchr** [comment]
If you put "\tuprints{}" you will get "uppertitleback" and the tuprints information, even if "twoside = false". So it will be automatically the second page.

I have just searched for a way to provide the information given in "uppertitleback" without the tuprints information.

**Comment by TeXhackse** [comment]
Interesting ;D I did not know it would exist in twoside anyway - but yeah seems like I implemented that some time ago. Will note that down.

You can overwrite all settings using KOMA-Scripts `\lowertitleback` since the mechanisms are set to be compatible with the defaults. There is no macro to access the the parts. I don't think this is a general requirement. You can add personalzed license data of any kind.
