### ISSUE TITLE
Several warnings that change font style

### ISSUE THREAD

**Issue by michaelkennecke** [tudace/tuda_latex_templates#384]
Hello,

my font style (the front formatting of section titles) has suddenly changed and I suspect it's because of one of these warnings:

![image](https://user-images.githubusercontent.com/48255296/179028603-7976e77b-881d-44c6-8ec2-b1ce3ae133ca.png)

**Comment by TeXhackse** [comment]
It seems like you use an old version. This might remove some of the warnings, probably not all, because the unknown slot number is simply the case since you seem to use glyphs which are not available in the font.

**Comment by michaelkennecke** [comment]
I am currently using the following version: "This is file `tudapub.cls' version 1.20-beta (2019/10/22)"

What is the easiest way to update without loosing my settings?

**Comment by TeXhackse** [comment]
There you got the answer for most of the issues. That's why it was a beta. 

Which settings do you mean? The one in the editor or did you yourself do changes within the sty/cls files? The latter one you should never do anyway. 

Since you have a TeX Live 2021 installed the version in there should be much newer than the current one. So probably deleting/moving the old version will already fix a lot of the issues. It seems like you load it from the directory itself anyway.

**Comment by michaelkennecke** [comment]
https://www.informatik.tu-darmstadt.de/datamanagement/datamanagement/dm_teaching/dm_teaching_thesis/dm_teaching_thesis_guidelines/index.en.jsp

I downloaded this template and load it into Overleaf. I was not aware that there is an official template from the university.

**Comment by TeXhackse** [comment]
I see. 

Do you know who is responsible for this template? Could you please tell them they should update the base files? Or tell them to contact me about it. Thing is if people create custom files using some old version I cannot ensure everything is working probably and they didnt even include some mechanism to update. Since custom adjustments are not included into my contract I cannot do this without them talking to me. 

Beside this: In case you/they didn't do any changes to the sty files you should be able to replace them by the current release ones. 

You can overwrite the setting to use the local files by removing the line 
```
$ENV{'TEXINPUTS'}='./tex//:' . $ENV{'TEXINPUTS'};
```
from latexmkrc. In case you have installed a full TeX Live on your machine tuda-ci is already included there. That probably is not the most recent version but by far better than a beta from 2019.

**Comment by michaelkennecke** [comment]
Removing that line indeed solved my issue, thank you!

I will reach out to my supervisor and tell him to contact you. 

Best regards,
Michael

**Comment by TeXhackse** [comment]
Thanks. I will close this as resolved
