### ISSUE TITLE
\IfSolutionT not available anymore?

### ISSUE THREAD

**Issue by habernal** [tudace/tuda_latex_templates#386]
Hi all, I'm re-compiling my exams on a different machine now and installed the templates (unfortunately only versions prior to 3.0 work on Ubuntu 20.04 LTS... all newer versions fail because of some internal module, but that's a different story). So I installed the latest 2.11 version and can compile my exams with one exception: this macro doesn't exist (but it exists on my other computer with maybe some older version):

\IfSolutionT

is missing. What is the alternative to check if this is the solution version or not? (I'm using this to set a watermark)

**Comment by TeXhackse** [comment]
Well… old versions don't support new mechanisms. That is true. I'd be interested what doesn't work with the newer versions. 

Easiest would be to install a current TeX Live on your machine. This is possible on Ubuntu as well you just have to use the TeX Live installer instead of the package management.

See e.g. https://tug.org/texlive/acquire-netinstall.html for more information on that approach. Ensure that you uninstall the Debian/Ubuntu package before that.

**Comment by habernal** [comment]
Thanks.

> What is the alternative to check if this is the solution version or not?

**Comment by habernal** [comment]
Never mind, I hacked it myself wit another macro.

**Comment by TeXhackse** [comment]
Hm… sad I'd have preferred to build a solution which is compatible to the current version. Since the information you had why it does not work was a bit … lacking the point. I could not do that. Offer to do so is still valid.
