### ISSUE TITLE
Toggle some warnings, e.g., imrad

### ISSUE THREAD

**Issue by ahueck** [tudace/tuda_latex_templates#39]
I am using the *tudapub* class and the warnings about the imrad labels are a bit distracting:
````
/shared/apps/texlive/2019/texmf-dist/tex/generic/hyph-utf8/loadhyph/loadhyph-de-1996.tex: Package TUDaPub Warning: You did not provide a Label for key introduction.
/shared/apps/texlive/2019/texmf-dist/tex/generic/hyph-utf8/loadhyph/loadhyph-de-1996.tex: Package TUDaPub Warning: You did not provide a Label for key methods.
...
````
I also get warnings, which I am not sure if it is related to tudapub, about scrlayer

I am using silence, but it fails for the imrad label warnings:
````
\RequirePackage{silence}
\WarningFilter{scrlayer}{change of layer mode could result in unexpected}
\WarningFilter*{TUDaPub}{You~did~not~provide~a~Label~for~key~introduction.}
\documentclass[...]{tudapub}
````

Can these somehow be suppressed? 
(And maybe as a secondary questions, are these required when publishing?)

**Comment by TeXhackse** [comment]
This Feature and also the fact that it's active by default was requested by your library. 
You can disable the warning by using `IMRAD=false`.

The easiest and also expected way is adding those labels as descriped in the DEMO-TUDaPub.pdf.
The filter mechanism of silence won't work since it is only designed to silence outfashioned LaTeX2e warnings.
