### ISSUE TITLE
Why is there so much empty space at the bottom of pages?

### ISSUE THREAD

**Issue by timakro** [tudace/tuda_latex_templates#393]
You can see an example of this here:
https://sharelatex01.ca.hrz.tu-darmstadt.de/templates/625479119af27d0092fd0386/v/0/pdf?inline=true&name=TUDaThesis-3.23

Just wondering if this is a consequence of the corporate design rules or a stylistic choice. The spacing seems a little excessive to me.

**Comment by TeXhackse** [comment]
The corporate design itself is using a really small fontsize (8pt) and extremly small margins. So no, it's not in the guideline. 
Since the thesis template is created for use with more complicated content we decided to focus on readbility and therefore changed the margin setup to match typographic principles. 

In case you are interested in further details on this have a look at the concepts of page layout calculation using typearea (english translation: http://mirror.ctan.org/macros/latex/contrib/koma-script/doc/scrguide-en.pdf#page=27   german text: http://mirror.ctan.org/pub/tex/macros/latex/contrib/koma-script/doc/scrguide-de.pdf#page=27)

So the margins depend pn the papersize. Most books are not printed in A4 therefore the margins seem to be huge, though it's a basic princible of page layout constructions that half of the page is used for the text itself. 

In case you need to modify the margins there exist plenty of options, one would be increasing the `DIV` factor as described in the resources above or manually editing the margins with geometry.

**Comment by timakro** [comment]
Thanks for the detailed response. That seems reasonable, excuse my lack of knowledge about layout :)
