### ISSUE TITLE
Hardcoding of robotolf in font file

### ISSUE THREAD

**Issue by Jackd4w** [tudace/tuda_latex_templates#400]
Is there a reason why the "lining" font in [tudafonts.sty](https://github.com/tudace/tuda_latex_templates/blob/main/tex/tudafonts.sty#L53)  is hardcoded instead of being dynamic with respect to the chosen sans-serif font family? Since it is hard coded, switching from "Roboto" to the "FrontPage" font recommended in the corporate design is impossible without interfering with the package code. If a dynamic linking is not possible, could a check for a user defined sans-serif font be made? For example if the user uses the \setsansfont command provided by fontspec.

**Comment by TeXhackse** [comment]
The reason it's hardcoded is because it's not possible to choose a lining figure feature dynamically. The way it's selected depends on a bunch of options. Roboto was approved by the communicaions department so there is no difference between the recommendations. 

If you want to use another font one would usually disable the package loading mechanism. 

What you can do about it is redefine the macro within your personal font setup. Or simply disable the use by overwriting the titleinfo font:

```
\newkomafont{titleinfo}{}
```

It would be possible but complicated to check the loaded font at the beginning of the document. So I decided not to do this to reduce the maintenenace effort.

**Comment by Jackd4w** [comment]
Thanks, overwriting the titleinfo-font worked :)

**Comment by TeXhackse** [comment]
In case you rely on PDF/A you should take care of the font setup. I remember we had some issues there with the FrontPage fonts because some metrics were missing. Roboto doesn't have those issues.
