### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by daveekr** [tudace/tuda_latex_templates#403]
Hello,

our department requires a "1.5" line spacing. I already read #308, however the suggested solution with `\onehalfspacing` is unfortunately also applied to ruled headings. This makes the headings just look like blown up and is not acceptable for me. I am aware of the whole Word 1.5 / LaTeX 1.5 line space debate and also know a strenuous work-around for this problem (surround every paragraph with `\begin{onehalfspace}` and `\end{onehalfspace}`). However I really want to avoid this kind of hardcoded work-around. Isn't there any solution to this problem? In theory it would be sufficient to exclude headings from the applied line spacing. It is frustrating to fiddle with line spaces and I really feel like, this should be some kind of configuration parameter, as it is required by some departments.

Additionally I experienced that Word is the _reference_ for most people. So people are comparing Word documents with 1.5 line spacing with LaTeX documents with `onehalfspace` and complain that the LaTeX document does not have 1.5 line spacing. I can understand both sides, but I really think there should be an option to apply the crooked Word 1.5 line spacing to a document, in an easy reproducible manner.

I am grateful for your thoughts and suggestions.

**Comment by TeXhackse** [comment]
It would be possible to use the hooks at the headings for this

```

\newcommand*{\ignoreArg}[1]{\relax}% or expl3's \use_none:n 
\AddtoDoHook{heading/begingroup}{\singlespace\ignoreArg}
````

See KOMA-Script documentation for details on this. 



Concerning the comparison TeX to Word:

Word is rounding the value. So it's not an option to make a rough setting. Then you would even have to change all the font sizes from pt to bp. (1pt in Word is 1/72 in and 1pt in TeX is 1/72.27 in).  I think generally using Word as a reference is just wrong there. Especially since the spacing depends on the version used and might change with any update.

**Comment by daveekr** [comment]
Hi, thank you for the quick response. The suggested solution does not work for me. With the suggested solution, the line spacing is applied to the title page, but not to the text corpus. The line spacing should only be applied to the text corpus not to headings or the title page.

**Comment by TeXhackse** [comment]
Have a look at the not on setspace in the thesis template. The title resets it. You have to enable it after the title material.

In most cases you even want to enable it after the toc.

**Comment by daveekr** [comment]
Thanks, that made the trick. :) However, I really think there should be a configuration parameter in the document class for this or at least some kind of documentation how to achieve this.

**Comment by TeXhackse** [comment]
Thing is … there are thousands of variants for different requests concerning the linespacing. And also it's not clear how to measure the 1.5 like you mentioned before. 

That's why we did not add it as a feature. I will add the note about the title spacing to the other information concerning setspace. That's a good point.
