### ISSUE TITLE
\setminus translated as U+29F5 ⧵ REVERSE SOLIDUS OPERATOR  causes problems

### ISSUE THREAD

**Issue by Mariusz-W** [tudace/tuda_latex_templates#409]
Unicode-math translates  \setminus  as Unicode REVERSE SOLIDUS OPERATOR, U+29F5 , instead of Unicode SET MINUS, U+2216 . This may have been intended though this clash with the Unicode specification has adverse consequences. One of them is that the authors of Math Fonts and the corresponding LaTeX packages are likely to conform to Unicode rather than to Unicode Math. They may even decide not to render the character U+29F5 at all. This is precisely the case with

 TeXGyreBonumMath  and  TeXGyreScholaMath

which resulted in making several mathematical expressions in some of my works incomprehensible to the reader who saw blank space in place of the missing characters.

I suggest to make  unicode-math  treat  \setminus  as  Unicode SET MINUS .

**Comment by TeXhackse** [comment]
Thanks for reporting, though this is not really a tuda-ci issue. Rather a unicode-math one. I think it's not a good idea if we redefine it. 

It's known since long, see https://github.com/wspr/unicode-math/issues/181 
Within that issue there is also a PR requesting that change.  I think it might be best to add you comment there. Otherwise I can also put some effort into that discussion to get that change.

**Comment by Mariusz-W** [comment]
I apologize for pasting my report in a wrong place. You can remove my report.

The matter I reported is an obvious issue. Of course, it must have been reported before (Thank you for providing the link to the original report). The only thing that is strange, is a stubborn resolve of the author of the wonderful unicode-math package not to fix that obvious gaffe. I was reminded of this old issue when students reported incomprehensible formulae in my lecture notes. My first reaction was to withdraw the text of the notes. A later investigation revealed that this was due to some Math fonts don’t even have the glyph attached by unicode-math to \setminus  while having, of course, the Unicode SET MINUS .

**Comment by TeXhackse** [comment]
You are totally right on this. And I know it's not a good option at all. I will leave this issue here open until it's adjusted in unicode-math. Maybe that's simplifying the process for others. 

Still its of course possible to patch that externally. But I don't think it's a good idea at all. Probably it will help to remind below the issue in unicode-math that stix did that change and it would now really be up to unicode-math to adapt that.

**Comment by schoeps** [comment]
@TeXhackse I assume that redefining this symbol is only a one-liner? Can you post it here?

**Comment by TeXhackse** [comment]
It's a bit more complicated. Usually unicode-math is saving the definitions into a table. The easiest way would be to copy the `unicode-math-table.tex`  to the local directory and edit it. Otherwhise it will be a bunch of definitions to attend those to already existing ones. 

You can copy the file by

```
cp $(kpsewhich unicode-math-table.tex) .
```

And then have to change the defintion of 
```
\UnicodeMathSymbol{"2216}{\setminus                 }{\mathbin}{reverse solidus operator}%
```

**Comment by Mariusz-W** [comment]
@schoeps

The relevant line in the  unicode-math-table.tex  file where  unicode-math  sets up the translation table between the LaTeX/amsmath  macros and the Unicode codepoints, is this: 

`\UnicodeMathSymbol{"029F5}{\setminus                 }{\mathbin}{reverse solidus operator}%`

For  unicode-math  to be in agreement with  Unicode  , it would have to be:

`\UnicodeMathSymbol{"02216}{\setminus                 }{\mathbin}{set minus}%`

**Comment by TeXhackse** [comment]
yep, you are right, did t change it complelty. edited now.

**Comment by schoeps** [comment]
Thank you both. I thought it would be helpful for others to find this solution here (even if "hacky").

**Comment by schoeps** [comment]
Finally, we had the same issue today and we cooked up this workaround: `\AtBeginDocument{\renewcommand{\setminus}{\mathbin{\backslash}}}`.
 The result may not be the correct symbol but is visually a sufficiently close approximation for us. 

@TeXhackse Any recommendations or known drawbacks?

**Comment by TeXhackse** [comment]
It will not survive a math font change. And you will also break the direct unicode input support unicode-math provides. 
So it's not a general solution.

Beside this it will not be working with any kind of accessibility setup by replacing the char. but since the old one is not matching either that's already broken anyway.

**Comment by schoeps** [comment]
> It will not survive a math font change. And you will also break the direct unicode input support unicode-math provides.
So it's not a general solution.

Can you explain this a bit more? I would expect that in all fonts the two symbols should be visually similar.

The other point is clear to me.

**Comment by TeXhackse** [comment]
Have to check again - but at first sight this also seems to be resolved … actually I didnt check for long :/ sorry
