### ISSUE TITLE
Set localized signature date in affidavit

### ISSUE THREAD

**Issue by DrauzJu** [tudace/tuda_latex_templates#413]
Hi, 
is there a way to set the signature date in a thesis affidavit?
`\submissiondate{...}` changes it, but since my main language is English, the date is then displayed in English on the German affidavit.

Thanks for any help!

**Comment by TeXhackse** [comment]
By default it's the submissiondate. There are not two separater variables You can simply manually set it by setting the submissiondate later. It's a string. You can insert anything there.

Since you mention the language setting

```
\foreignlanguage{ngerman}{\today}%doesn't change the date
{\selectlanguage{ngerman}\today}% changes the date
```
Independently you can always use the ISO format. According to DIN5008-2020 this is now the preferred date format anyway.

```
\the\year-\the\month-\the\day
```

**Comment by DrauzJu** [comment]
Perfect, thanks for the quick response!
