### ISSUE TITLE
Spacing header / headline issue

### ISSUE THREAD

**Issue by astrovn** [tudace/tuda_latex_templates#429]
Dear Team, 

I would like to know if there is any option to customize the spacing between a chapter headline? In my tuda report is this space very large which leads to the effect, that I can't place large tables at the same page as the headline. Especially for the appendix this is critical, as I get first an empty page just with the chapter/section headline and then a second page with the table. How can I solve this issue without splitting up the table (which would result in just 2 lines at the next page...)?

Thank you for your advice.
Cheers, VN

**Comment by TeXhackse** [comment]
That's a general KOMA-Script feature. Please have a look at the documentation. Keyword to look for is `\RedeclareSectionCommand` there you can adjust the spacing. I'd recommend to only do this for the appendix. 

An additional way would be to set `\KOMAoptions{open=any}` for the appendix, so chapters may also open on left pages. This depends on the structure of your document.  Additionally it might be an option to use large headlines for the appendix sections and the captions to name/reference the elements instead of separate sectioning.

**Comment by TeXhackse** [comment]
Closing as there was no further information and i think it's resolved. @astrovn in case it's not feel free to reopen or move to discussions, since it's a customization.
