### ISSUE TITLE
Package xcolor clashing with tudapub.cls

### ISSUE THREAD

**Issue by JuLateX** [tudace/tuda_latex_templates#44]
Hello,

I need to use the `xcolor` package to plot figures with tikz. I added the package as follow: `\usepackage[cmyk,dvipsnames]{xcolor}`, before the `\usepackage{tikz}` to avoid clashes between the two packages. However, when compiling, I get the following error message: 

> Option clash for package xcolor.

It refers to the file tudapub.cls on line 29.

Could you explain me how to prevent this crash?

Thank you.

**Comment by TeXhackse** [comment]
tudapub requires xcolor and tikz itself.

You can add the Options by switchching to
```
\PassOptionsToPackage{cmyk, dvipsnames}{xcolor} 
```
before loading tudapub. 
It would be possible to add a PassingOption to tudapub as well. But I think for this case this wouldn't be necessary.

Plase pay attention to the fact, that pdfa-mode will switch to rgb colors. You should turn that one off for cmyk.

**Comment by JuLateX** [comment]
tudapub is loaded within `\documentclass[options]{tudapub}`, right? So should I put this comand line
`\PassOptionsToPackage{cmyk, dvipsnames}{xcolor}`
before `\documentclass`?

**Comment by TeXhackse** [comment]
Yes.

To add a short explanation:
if you load a package twice with a different set of options, you get an option clash.
That's why you receive one as soon as loading xcolor yourself.
`\PassOptionsToPackage` adds the options to the options list to be loaded in case the package will be loaded later. Therefore you have to add it before loading the package which means before documentclass.


tudapub already choses cmyk mode, except you have the pdfa mode switched on. This is due to pdfa requires rgb, since it focusses on the digital storage and not printing.

The dvipsnames option isn't loaded so you can also get the desired setup by simply turning pdfa to false and adding `\PassOptionsToPackage{dvipsnames}{xcolor}`

This generally is the way to do it, when you want to add any option to any automatically loaded package.
