### ISSUE TITLE
table of contents in beamer design2023

### ISSUE THREAD

**Issue by towadroid** [tudace/tuda_latex_templates#447]
Hi, regarding the new design for the slides, I have to customization requests regarding the appearance of `\tableofcontents`?

1.  I would like to have a larger font size for the section titles, however `\setbeamerfont{section in toc}{size=\Huge}` doesn't seem to have any effect.

1. In addition, subsections look really weird (same font size, no bullet point, just right below the section title). Would it be possible to change this?

Thanks!

**Comment by TeXhackse** [comment]
Yes it is possible to change that but it's not part of the design, so it will never be officially supported nor part of the design, since this is something I may not decide. 

1. You also have the elements `section number` and `section title` in beamer. Here the font is set via `section title`
2. 
3. Since the whole mechanism is not officially supported it's a bit hard. You can of course redefine the subsection in toc. I requested an official solution but did not yet receive anything.  You can enable the numbering for subsections there, we didn't do that by default, since it's usually not done in beamer presentations at all.

**Comment by schoeps** [comment]
@TeXhackse There are some improvement w.r.t. subsections in the repository that are not yet in texlive etc? If yes @towadroid may want to look to into this? 

(I haven somewhat given up and "flattened" the toc of my lectures)

**Comment by TeXhackse** [comment]
@schoeps None of the design 2023 is in TeX Live because I still have to wait for the permission to release. I will re request that today. 

The structure @towadroid was describing sounded like the last version. This should switch to a single column toc, does it?

**Comment by TeXhackse** [comment]
Generally one can enable numbers for the subsections as well, this will be documented. I now added a mode to support the use of itemize items. 

They can globally be set via 

```
\setbeamertemplate{subsection in toc}[TUDa][numbered]% prinnt the subsection number
\setbeamertemplate{subsection in toc}[TUDa][itemize]% itemize style
\setbeamertemplate{subsection in toc}[TUDa]% default no element but custom ones would be possible 
``

Feedback is welcome. I still don't have an official answer concerning that. So it might be the case I have to remove it though the mechanism to keep it extendable can be included for sure.
