### ISSUE TITLE
Custom margins for specific pages

### ISSUE THREAD

**Issue by Morbuch** [tudace/tuda_latex_templates#448]
I am writing a cumulative PhD thesis, so I need to include external pdfs that make up the results chapter. I have an issue now regarding the margins of the `tudapub` document. I would like to keep the default large margins for the whole text, but just for the included pdfs, the margins should be rather small. Using the standard margins would lead to very tiny fonts in the embedded text. I also would like to show overall page numbers and have the bar on top of the included pages, so it still looks like a part of the document.

I did this successfully in the document class by using the `geometry` and `pdfpages` packages and then defining a new geometry just for the pdf inclusion, similar to this:
```
\newgeometry{left=25mm,right=25mm}
\includepdf[pages=-, pagecommand={}, noautoscale, width=\textwidth]{file.pdf}
\restoregeometry
```

But when trying the same with the `tudapub` class, it works only partially (with `custommargins=geometry`). The included pdf is scaled according to the new margins, but the TU style bars and page numbers are still at the same place and overlap with the pdf.
Is there maybe a command which readjusts the position of these elements to the new margins?

**Comment by Morbuch** [comment]
Nevermind, I did it:
```
\includepdf[pages=-, pagecommand={pagecommand={\thispagestyle{plain}}}, noautoscale, width=\textwidth]{file.pdf}
```
The pagecommand entry was the key. Sorry for bothering you, maybe this might be useful for others with the same problem.

**Comment by TeXhackse** [comment]
Since your answer is not really a solution to the question I still want to add something.

`\newgeometry` is only adjusting the values you change. So the headline and footline will keep their measures when you do that.  the current implementation in tudapub is settting the width to a fixed value and is not always recalculating that. I will change it, so it automatically works as intended, because you are right, and the width should be adjusted, generally this is possible thing is, we currently lack the notification to TUDa-CI to realize this difference. 

So what works is informing TUDa-CI about the change by doing a reinit of the head/footwidth:

```
\newgeometry{margin=3cm}
\KOMAoptions{headwidth=text,footwidth=text}
```

As the current behaviour is not intended, and works different from the base package I mark this as a bug. Thanks for reporting.
