### ISSUE TITLE
Wrong display of accentcolor option (CMYK vs. RGB)

### ISSUE THREAD

**Issue by ruben-mal** [tudace/tuda_latex_templates#456]
With the current version of the design the accentcolor option does not display the correct color. There are even differences in the color between different document classes.

As an examples:
accentcolor 11b should display as **#721085**

When using `DEMO-TUDaThesis.tex` it displays as **#4c00ff**
When using `DEMO-TUDaBeamer.tex` or `DEMO-TUDaReport.tex` it displays as **#6f2c91**

**Comment by TeXhackse** [comment]
It depends a lot on the color model used. Please be aware that there is no direct conversion from RGB (or HTML) colors to CMYK. 

As that's the difference between the documents it probably also is the reason you get weird codes out of it. 

I will have a closer look as soon as possible to ensure. But just having a look at the values, this is the most obvious reason.

**Comment by TeXhackse** [comment]
Maybe I should add an example on 11b: 

So if I use the CMYK setting I get that one: https://www.w3schools.com/colors/colors_picker.asp?colorhex=4d00ff Since my display is using only rgb, it looks far more blue. 

For the RGB setting directly I get: https://www.w3schools.com/colors/colors_picker.asp?colorhex=721071 Which is more what you would expect.

**Comment by ruben-mal** [comment]
Thanks for having a look. I get the point that different color spaces  may introduce problems.

I just wanted to mention that there must have been some change from **v3.35** to **v3.36** since using the older `tex` folder from **v3.35** results in the correct colors for me when using `DEMO-TUDaThesis.tex`.

**Comment by TeXhackse** [comment]
Ah Isee. Thanks for the explanation and getting in touch. I will have a look and take care of it probably tomorrow.

**Comment by larsfw** [comment]
I had a similiar issue with the accentcolor `3c`. It appeared more green and lighter, whereas a couple days ago it was displayed right (RGB:(0,136, 119)).

Thank you for the workaround with ` \RequirePackage[RGB]{xcolor}`, now it is displayed correctly again. 

Just want to add that I had to set it before `\documentclass[...]{tudapub}` in order to work.

**Comment by TeXhackse** [comment]
@larsfw  Oh - thanks - you are right. Actually that's what i wanted to write there and failed. I edit it to avoid confusion.

**Comment by schoeps** [comment]
> Thank you. I am trying to switch from the internal Sharelatex instance to overleaf.com for the GitHub and Zotero integrations and ran into this color problem. Adding `\RequirePackage[RGB]{xcolor}` fixed it for me.

The reason why old problems may appear newly on overleaf is that they not have the latest version of TUDaPub. You can fix this as suggested, or install a newer version of the package locally, but this can be tedious if dependencies also need updates.
