### ISSUE TITLE
citations not found

### ISSUE THREAD

**Issue by larsfw** [tudace/tuda_latex_templates#463]
Hi, 

the citations in my thesis worked fine this afternoon, but now, without making any changes, my bibliography is not printed anymore and I get the following issue for every citation:

"You have cited something which is not included in your bibliography. Make sure that the citation (\cite{...}) has a corresponding key in your bibliography, and that both are spelled the same way."

Same thing with your demo project as well. The .bib files are fine, as I said, I made no changes. I already had this issue before, about two weeks ago, and then a couple days later it worked again.

When I type "\cite{}" in the editor I get all my entries of the .bib file listed as suggestions.

![2024-02-20 22_sharelatex](https://github.com/tudace/tuda_latex_templates/assets/84448238/04939678-3a8e-489b-99a1-f036f95696db)

Do you have any idea why this happens? I would like to compile a draft tomorrow including my bibliography.

**Comment by TeXhackse** [comment]
depends on your setup. Usually this happens when the BibTeX/Biber output is not created correctly due to a syntax error. If you don't start it manually it also might be the reason, that the LaTeX compiler faced an error and therefore the bib process has not even been started. 

Check the logfiles, check the bibtex/biber log as well. Usually they should show you a reason.

**Comment by larsfw** [comment]
Thank you for the quick response! I use sharelatex on the tu-darmstadt domain.

It says the following in the raw logs:

```
LaTeX Warning: There were undefined references.

Package rerunfilecheck Info: File `output.out' has not changed.
(rerunfilecheck)             Checksum: D41D8CD98F00B204E9800998ECF8427E;0.

Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                output
(biblatex)                and rerun LaTeX afterwards.

Package logreq Info: Writing requests to 'output.run.xml'.
\openout1 = `output.run.xml'.
```
I don't know how to rerun Biber. I cleared the cached files and recompiled but that didn't solve it.

**Comment by TeXhackse** [comment]
I had a quick look at sharelatex. I am not responsible for it, so you should ask the sharelatex support.

But you are right, it seems like biber is failing there. I don't have access to the server logs, so I can't say anymore but that I expect it to not be your fault.

One can usually enforce to run biber via the latexmk config, but this also is failing. As I don't get any log for this as well it only claims to be failing, the issue seems to be on the server side and there is nothing I can do about it.

**Comment by larsfw** [comment]
Ok, I will ask the sharelatex support. Thank you!
