### ISSUE TITLE
Sublogo in tudapub

### ISSUE THREAD

**Issue by juppees** [tudace/tuda_latex_templates#47]
I am currently trying to convert my thesis, started in the old TU design packages to tuda-ci, but I didn't find any option to add the institution´s logo as the only info box. Is there an easy way to achive this?
Adding the institution logo with \addTitleBoxLogo*{} as documented in the TUDaPub.tex also adds the department and institution as a separate text box what is not my intention.

**Comment by TeXhackse** [comment]
There is no mechanism too add Logos to the footer as you referred to for the Flyer variant in the original Variant of your issue. As you might have already realized due to the edit.

There is a possibility to reset the department and institution boxes. Though this feature is not documentated to not encouraged people to use it. Since it's somehow an offence against the official guidelines. 

You can set the instboxes to empty by using the option
```
instbox=false
```
Beside that using `\addTitleBoxLogo` should do its job.

**Comment by juppees** [comment]
Thank you very much, `instbox=false` did the job. My intention was only to get rid of the box with department and institution in written form and replace this by the institution´s logo like it is shown in the corporate design handbook on pages 25 , 30 and 33.
Also on page 33 (4.10. Zusatznennung von Fachgebieten):
> Darstellung von Fachgebieten der TU Darmstadt: Das Logo oder die Institutsbezeichnung steht immer unter der Wort-/Bildmarke der Technischen Universität Darmstadt.

As I understand it, both solutions are allowed - either in written form or as logo. As far as I know and from my own personal experience, this is several institutions´ practice and therefore it might be beneficial to be documented.

**Comment by TeXhackse** [comment]
I thought so, already added a note on that to the development state.
