### ISSUE TITLE
Add note on t option for tudabeamer

### ISSUE THREAD

**Issue by SamuelePolimi** [tudace/tuda_latex_templates#55]
I have the following code

```
\begin{columns}
	\begin{column}{0.45\linewidth}
		\includegraphics[width=0.8\linewidth]{plots/robot2.jpg}
	\end{column}
	\begin{column}{0.45\linewidth}
		\begin{itemize}
			\item Item a
			\item Item b
			\item Item c
		\end{itemize}
	\end{column}
\end{columns}
```

which is not displayed correctly. In particular, the items are displayed in the correct column but only below the image. 

In attach a complete example [minimal example.zip](https://github.com/tudace/tuda_latex_templates/files/3746800/minimal.example.zip).

**Comment by TeXhackse** [comment]
I will have a look at that, currently working on tudabeamer anyway.
As a quick workaround you can use the T option for columns:
```
\begin{columns}[T]
```

**Comment by SamuelePolimi** [comment]
Thank you very much for the very quick reply. The workaround is effective!

**Comment by TeXhackse** [comment]
Well the action happening is due to the different baseline of image and text. The baseline for an image is usually at its bottom. The tudabeamer.cls sets the alignment for the frames to `t` according to the guideliens. Therefore the alignment for the frame itself is `t` by default as well. `t` alignment means that the first baseline shall be aligned to each other.

This also happens in beamer per default. You can verify this by replacing the class and setting the t option for beamer. 

You can handle that issue either by globally setting the `c` option or adding that either to the columns environment or the frame containing the columns.

I will add information about that to the documentation.

**Comment by SamuelePolimi** [comment]
Thanks!

**Comment by schoeps** [comment]
If you do so (which is not strictly necessary since it's a standard latex issue) then also mention "onlytextwidth". I think this is also often unknown :)
