### ISSUE TITLE
prepare_tuda script not working

### ISSUE THREAD

**Issue by melhindi** [tudace/tuda_latex_templates#58]
Hi,
I tried to run the prepare_tuda.script, however it seems to have certain undocumented assumptions...
1) First I got this error `! LaTeX Error: File tudabeamer.cls not found.` - turns out that an latexmkrc is missing in the `example` folder
2) After adding a custom latexmkrc, I am getting various `Undefined control sequence.` error for various example files

**Comment by TeXhackse** [comment]
prepare_tuda is a Variant to prepare the bundle for TU Darmstadts intern uploads. It is not marked as such, because it is not actually part of the Release. Due to that this file is not intended to be used outside it's environment it's just stored to simplify the Release workflow.
You don't need it to use tuda-ci.
