### ISSUE TITLE
Getting countless errors @ line 2392 of pdfx.sty

### ISSUE THREAD

**Issue by PhilK-7** [tudace/tuda_latex_templates#66]
When I first tried the package, it worked well (template tudapub). 
But after some time, regardless of the changes, I cannot compile anymore and get many errors, with most being in **line 2392 in pdfx.sty**

The weird thing, when this happens, even when I revert my document back to a point where it worked, and even when I try to compile _one of the demo files_, I get the **exact** same errors again.

I'm using TeXstudio and tried MikTeX as well as TeXLive, with the exact same results. It seems to not be an issue with the pdfx package, as I reinstalled it multiple times.

[https://postimg.cc/TL4dbtn3](url)

**Comment by TeXhackse** [comment]
Could you please attach the complete log file?

**Comment by PhilK-7** [comment]
[DEMO-TUDaThesis.log](https://github.com/tudace/tuda_latex_templates/files/3800703/DEMO-TUDaThesis.log)

**Comment by TeXhackse** [comment]
I guess you are either using a macro or a different type of special formatting inside one of the title fields. This data is going to be written to the metadata, if pdfa mode is enabled. see #62 for some more info. If you want to stick to pdfa please add different data using the `\Metadata` macro. 

The problem is, that Metadata cannot use LaTeX macros, because it's just a string. 
You can open the generated `\jobname.xmpdata` file so see the misstake.
We could bypass that just passing the string directly, but usually this is not the desired solution. Therefore I decided to stick with the different mechanism for metadata.

If this helps, please close this issue.

**Comment by PhilK-7** [comment]
Indeed putting special formatting stuff in the title seems to be problematic. 
No idea why I got tons of errors in the pdfx package file, but it all works now.

Thank you
