### ISSUE TITLE
Small Caps not working in Bibliography

### ISSUE THREAD

**Issue by pvogt09** [tudace/tuda_latex_templates#69]
When using 
```tex
\renewcommand*{\mkbibnamefamily}[1]{\textsc{#1}}
```
for author names in small caps in the bibliography, the font of the familiy name is somehow changed, but not changed to small caps. A MWE can be generated by using `DEMO-TUDaThesis.tex` and adding the above line. `\textsc` in normal text works as expected.

**Comment by TeXhackse** [comment]
I am sorry, I cannot reconstruct that. For me everything works fine. 
The upper one is using your code the lower one is normal textsc.

![image](https://user-images.githubusercontent.com/10723888/68401211-a179b500-0179-11ea-910e-5193faebeea1.png)

**Comment by pvogt09** [comment]
[DEMO-TUDaThesis.log](https://github.com/tudace/tuda_latex_templates/files/3824074/DEMO-TUDaThesis.log)

**Comment by TeXhackse** [comment]
The XCharter package on your system seems to be outdated v1.112 (2017) current version is 1.202. Since you use MikTeX this should easily be able to be resolved by an update. 
The sc font is working on MikTeX as well as on TeX Live. I did not try your specific Version, but also tried a 2018 one.

If this problem keeps existing, please let me know. During that I will close this one, since it's not related to my sources as far as I can see.
