### ISSUE TITLE
URspecialopts

### ISSUE THREAD

**Issue by schoeps** [tudace/tuda_latex_templates#70]
Shall we ship a copy of `URspecialopts` (possibly under a different name) with the package? The package `urcls` is not installed by the default latex installation (playing with ubuntu eoan).

**Comment by TeXhackse** [comment]
we would have to do the same for some fonts then as well + your pgfplotsthingie also might require some specials. I think the note on that one we added should be enough. Talked about that to @marklaz before. Especially since tuda-ci is neither.

**Comment by marklaz** [comment]
To keep things manageable, I also would vote for a clear note in the documentation instead of integrating files directly.

What I wonder:
Will URspecialopts be installed automatically in LiveTeX and MikTeX, if tuda-ci is installed? 
If not, is there any mechanism to mark it as a required package explicitly? (Apart from any lines in the cls or sty files.)

**Comment by TeXhackse** [comment]
CTAN does not have any dependency management. This is due to the fact, that it would require demo files testing all features.
But usually if you want to stick to a minimal LaTeX installation you get the message about the missing package and can install it using tlmgr or manually.

Anyway in most cases I would recommend to install a full texlive installation anyway. This bundle is not the only one depending on special packages. Everyone who wants to keep his installation minimal has to do dependency checking on his own anyway.

What I already suggested would be adding compiling packages as required by Overleaf. This would also be a possibility to use the bundle out of the box without installation.

**Comment by TeXhackse** [comment]
If the note in the README is not enough, I could adjust a specific error message if that package is not found. Though I think it's kind of confusing adding a special message for one package, while all the others could cause the same problem. For more specific distros it already is facing the same error for more packages. Those people usually just know about that.

**Comment by schoeps** [comment]
Ok! 

Background: I tried to make circleci compile our templates with ubuntu eoan and the package `texlive`. I did not find a docker image with texlive-full and gnuplot. When I install `texlive-full` then the installations needs >10min, so I was hoping to find a cheaper solution. Anyway, I will close this issue.
