### ISSUE TITLE
Bei Verwendung von TUDAThesis ist die Fußzeile zu hoch

### ISSUE THREAD

**Issue by Rosegirl123** [tudace/tuda_latex_templates#76]

**Comment by Rosegirl123** [comment]
![TUDA_Vergleich](https://user-images.githubusercontent.com/46976373/68684560-fa29c300-0568-11ea-953a-bdb518ba1882.PNG)

See picture, on the left side example file for TUDathesis on right side for TUDapub. 
 I guess the design rules for the line on the end of a page are still the same for thesis and publications? 

Best Regards and thanks for support, 
Rosegirl

**Comment by Rosegirl123** [comment]
![Das Bild der TU Darmstadt S31](https://user-images.githubusercontent.com/46976373/68688955-f3527e80-056f-11ea-844a-e8a528e31568.PNG)

According to TU Darmstadts Corporate Desidn Rules the distance for topline and bottom line are both noct set correctly. Should be as in TUDa Pup, but font size should be 11 pt

**Comment by TeXhackse** [comment]
The requirements for TUDaThesis have been chosen to improve readability. That's why the default setting has been set to `custommargins=true` and will use the typearea setup.
You can of course stick to the original setting by using the `custommargin=false`.

This is documented in the demo files and I was instructed to do it that way.
