### ISSUE TITLE
Package fontenc Error: Encoding file `t2aenc.def' not found.

### ISSUE THREAD

**Issue by piegamesde** [tudace/tuda_latex_templates#81]
When I try to compile the package (using the [AUR pkgbuild](https://aur.archlinux.org/packages/latex-tuda-ci/)), I get the following error:

```
! Package fontenc Error: Encoding file `t2aenc.def' not found.
(fontenc)                You might have misspelt the name of the encoding.

See the fontenc package documentation for explanation.
```

This has been reproduced on two different machines, one Arch Linux and one Manjaro. The package version is `2.01-1`. I cannot safely tell if this is an AUR issue or with this concrete tex package.

**Comment by TeXhackse** [comment]
You should probably have a look at #71 
Some lokal distributed latex template variants have been spreading buggy font definitions.

**Comment by piegamesde** [comment]
How can I fix this? `rm -r .texlive` did not help. (And I don't know really much about Tex in general)

**Comment by TeXhackse** [comment]
did you ever install any package manually? 

Your local texmf-tree can be found, by 
```
kpsewhich --var-value TEXMFLOCAL
```
afterwards you have to run
```
updmap-sys
```
maybe as root. depending on how you installed your distribution.

Without more information I cannot help any further, because I don't know your setup and linux distributions usually are not up to date, as far as TeX ist concerned. (And no, not even Arch ;-) )

You could add `\listfiles` to the document run it in batchmode and afterwards give me the log. Then I can maybe tell you more.

Anyway this is a general LaTeX thing, not related to tuda-ci.

**Comment by LCCardenas** [comment]
I managed to fix this issue on Arch by installing the package `texlive-langcyrillic`, which contains the file `t2aenc.def`. The solution was taken from [here](https://tex.stackexchange.com/questions/5079/what-is-wrong-with-my-cyrillic-text)

**Comment by pbertoni89** [comment]
> I managed to fix this issue on Arch by installing the package `texlive-langcyrillic`, which contains the file `t2aenc.def`. The solution was taken from [here](https://tex.stackexchange.com/questions/5079/what-is-wrong-with-my-cyrillic-text).

Me too on Ubuntu Jammy; package is `texlive-lang-cyrillic` actually
