### ISSUE TITLE
problems with LaTeX3e commands in tudafonts.sty

### ISSUE THREAD

**Issue by ma137** [tudace/tuda_latex_templates#85]
If I compile for example `DEMO-TUDaExercise.tex` or `DEMO-TUDaThesis.tex` (TUDa-CI v2.01) on Ubuntu 18.04 (TexLive 2017) with`pdflatex`, I get the following error:

>! Undefined control sequence.
><recently read> \cs 
>                    
>l.51 		\cs
>          _if_exist:NF \texteuro {\RequirePackage{textcomp}}

A solution is to add the lines
`\RequirePackage{expl3}`
`\ExplSyntaxOn`
directly after the line `\RequirePackage{anyfontsize}` in the file `tudafonts.sty`
As far as I understand, `expl3` is package providing LaTeX3e commands in LaTeX2e environments.

**Comment by TeXhackse** [comment]
Thanks for reporting. 

Yes, you are right, the testing mechanism is not implemented as I wanted it to. In the test case it worked, though tudafonts was loaded inside expl3-Syntax.

I've fixed that. Will Upload a patch soon.

Though I simply switched to `\ifx` since tudafonts doesn't require expl3 things in general.

**Comment by ma137** [comment]
I tried the the new version of `tudafonts.sty` from commit https://github.com/tudace/tuda_latex_templates/commit/b99fae383596adf157f9103df9a148b4a1071aa7. It works on my system.
Thanks for the fast bug fix.
